[CSUB-912] Add CLI EVM commands fund, send & withdraw
gluwa/creditcoin3 pull request #116
Opened 2023-12-04 19:00 UTC by pLabarta

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2023-12-05 13:13 UTC, atodorov requested changes
Definitely needs integration tests to exercise these 2 commands.

2023-12-05 13:36 UTC, atodorov requested changes
Some changes requested.

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/index.ts
> +        command.option('--evm-url [evm-url]', 'URL of the EVM RPC endpoint to connect to', 'http://127.0.0.1:9944');
Can this use the value of the parent `--url` parameter, possibly replacing `ws://` with `http://` ?

2023-12-05 13:36 UTC, atodorov commented on cli/src/cli.ts
> +    .addCommand(makeEvmCommand());
How about keeping the alphabetical order ?

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/index.ts
> +    cmd.addCommand(makeEvmSendCommand());
Alphabetical order ?

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/index.ts
> +    cmd.description('Interact with the EVM side of Creditcoin3');
Missing 2 commands IMO:

1) `show-address` - to show me my own address. Better yet implement it as another output message from `show-address`. That will help me discover EVM addresses of every Substrate address

2) Command to show me my current EVM balance. Probably best to implement as part of `balance`

2023-12-05 13:36 UTC, atodorov commented on cli/src/lib/evm/address.ts
> +}
Suggestion: everywhere where we deal with addresses allow the user to specify either a Substrate address or an EVM address and use these 2 functions internally to convert to the expected format for the actual operation. 

That will give lots of flexibility for cli users. It can be implemented in a subsequent PR/ticket though.

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/fund.ts
> +    const amount = parseAmountOrExit(requiredInput(options.amount, 'Failed to send CTC: Must specify an amount'));
Must check if `amount` > actual free balance minus expected fee. Otherwise the transaction above will fail.

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/send.ts
> +    const amount = parseAmountOrExit(requiredInput(options.amount, 'Failed to send CTC: Must specify an amount'));
Must check that `amount` is less than what the sender EVM account holds. 

Question: is the amount held by the EVM address tracked separately than the free balance on the Substrate side?

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/send.ts
> +    const amount = parseAmountOrExit(requiredInput(options.amount, 'Failed to send CTC: Must specify an amount'));
Q2: where is the gas fee deducted from? Is that from the amount the EVM account holds ? If so we'll need some extra checking to exclude the anticipated gas fee from the maximum amount which can be transfered.

Note: not sure that `requireEnoughFundsToSend` is checking the EVM side!

2023-12-05 13:36 UTC, atodorov commented on cli/src/commands/evm/withdraw.ts
> +        process.exit(0);
Makes more sense as part of `show-address` IMO.

2023-12-05 13:44 UTC, atodorov commented on cli/src/lib/evm/wallet.ts
> +        );
Question: I found out my EVM address and funded it. Then I found out the EVM address of another Substrate account and wanted to use the `evm send` command. How do I figure out what is my EVM seed phrase? 

Is that the same as my Substrate account or different ?

2023-12-06 13:24 UTC, pLabarta commented on cli/src/lib/evm/wallet.ts
> +        );
You don't have the seed to the associated EVM address. You *must* create an EVM account you control and fund that account to have control on the EVM side.

If you fund an EVM account associated to a Substrate account, you will only be able to withdraw those funds back to the Substrate account.

2023-12-06 13:25 UTC, pLabarta commented on cli/src/lib/evm/wallet.ts
> +        );
Opening a ticket for EVM/Substrate account management docs :eyes:

2023-12-07 17:17 UTC, pLabarta commented on cli/src/commands/evm/send.ts
> +    const amount = parseAmountOrExit(requiredInput(options.amount, 'Failed to send CTC: Must specify an amount'));
Each side pays for fees in its own way. But, after EIP-1559 (which Frontier supports by default now) gas fees a bit weird to calculate. Best we can do without going too crazy is a bit of heuristics. Looking into it atm.

2023-12-08 16:17 UTC, atodorov requested changes

2023-12-08 16:17 UTC, atodorov commented on cli/src/commands/evm/balance.ts
> +    cmd.description('Show balance of an EVM accoun');
Typo:

```suggestion
    cmd.description('Show balance of an EVM account');
```

2023-12-08 16:26 UTC, atodorov commented on cli/src/lib/evm/address.ts
> +}
^^^ I thought that 

```
wallet.address == evmAddressToSubstrateAddress(substrateAddressToEvmAddress(wallet.address))
```

that is, EVM <> Substrate conversion always yields the same results both ways.

I may need some more information on how this part works internally.

2023-12-11 13:27 UTC, pLabarta commented on cli/src/commands/evm/fund.ts
> +    const amount = parseAmountOrExit(requiredInput(options.amount, 'Failed to send CTC: Must specify an amount'));
This is checked by in line 30 by `requireEnoughFundsToSend()`

2023-12-11 14:49 UTC, atodorov commented on cli/src/commands/evm/balance.ts
> +    cmd.description('Show balance of an EVM accoun');
I still see the typo. Not sure if the commit which was fixing it got lost or something.

2023-12-11 14:53 UTC, atodorov requested changes
Minor change requested at this point.

2023-12-11 14:53 UTC, atodorov commented on cli/src/lib/evm/rpc.ts
> +    }
You can call `.replace()` unconditionally in a chain here. No need for conditionals.

2023-12-11 15:33 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +        expect(BigInt(balance.total.toString())).toBeGreaterThan(1);
Q: Do you mean greater than 1 CREDO or 1 CTC ?

2023-12-11 15:34 UTC, atodorov commented on cli/src/test/integration-tests/validatorCycle.test.ts
> +        );
Seems like a repeating pattern. Maybe a helper function will be a good thing to have here.

2023-12-11 15:45 UTC, pLabarta commented on cli/src/test/integration-tests/evm.test.ts
> +        expect(BigInt(balance.total.toString())).toBeGreaterThan(1);
Oh, it should be 1 CTC, good catch

2023-12-11 21:02 UTC, merged