Polkadot Release v1.1.0 patch
gluwa/creditcoin3 pull request #132
Opened 2023-12-18 22:09 UTC by frankli-dev

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2023-12-19 01:07 UTC, nathanwhit approved these changes

2023-12-19 10:15 UTC, atodorov requested changes
Need to update the whitelist for allowed forks to allow gluwa/frontier and gluwa/polkadot-sdk repositories.  This will fix the failure reported in https://github.com/gluwa/creditcoin3/actions/runs/7254387992/job/19763009568?pr=132. 

The rest looks good so far. Retesting Staking Dashboard against this PR!

2023-12-19 10:15 UTC, atodorov requested changes

2023-12-19 10:15 UTC, atodorov commented on Cargo.toml
> +sc-basic-authorship = { version = "0.10.0-dev", git = "https://github.com/gluwa/polkadot-sdk", branch = "release-polkadot-v1.1.0-patch" }
Opening a comment to track progress of staking dashboard retest against this PR:

2023-12-19 11:38 UTC, atodorov commented on Cargo.toml
> +sc-basic-authorship = { version = "0.10.0-dev", git = "https://github.com/gluwa/polkadot-sdk", branch = "release-polkadot-v1.1.0-patch" }
Unbonding from a pool now seems to show the correct amounts everywhere:

- when initiating the unbond
![01_unbond_shows_correct_amount](https://github.com/gluwa/creditcoin3/assets/1002300/f79f3e67-a049-4ecc-9839-83f2c7d14e61)

- on the progress bar
![02_unlocking_progress_bar_shows_correct_amount](https://github.com/gluwa/creditcoin3/assets/1002300/962215d8-c3d6-45ef-8f7b-df48f5972bb4)

- in the unlock modal
![03_unlock_modal_shows_correct_amounts](https://github.com/gluwa/creditcoin3/assets/1002300/c950bd8b-58ea-494c-9999-257a8f88d2eb)

- in Polakdot JS Apps
![04_polkadot_apps_shows_correct_amount](https://github.com/gluwa/creditcoin3/assets/1002300/2d3df316-83c8-4398-a698-546bde6275b8)

- unlocked funds shows correct amount
![05_unlocked_funds_shows_correct_amount](https://github.com/gluwa/creditcoin3/assets/1002300/17f2ec5e-5b74-426b-ad58-f24717216d2f)

- withdrawing also shows correct amount
![06_witdraw_modal_shows_correct_amount](https://github.com/gluwa/creditcoin3/assets/1002300/fad766ce-fd9c-416d-a959-f50095b55a10)

- total funds after withdraw looks correct as well (there were 33 CTC rewards claimed + fees)
![07_total_balance_after_withdraw_shows_correct](https://github.com/gluwa/creditcoin3/assets/1002300/406b3b3b-b764-4e73-b67d-57e9c6056160)

2023-12-19 11:40 UTC, atodorov commented
See https://github.com/gluwa/creditcoin3/pull/132#discussion_r1431291054 for detailed test results + screenshots!

2023-12-20 10:14 UTC, atodorov approved these changes

2023-12-20 11:39 UTC, merged