Draft: Testnet release 3.12.0
gluwa/creditcoin3 pull request #155
Opened 2024-01-04 17:07 UTC by pLabarta

# Description of proposed changes

Update testnet branch to prepare first testnet release

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-01-05 17:00 UTC, zacharyfrederick approved these changes

2024-01-05 17:53 UTC, zacharyfrederick requested changes
Reviewing locally

2024-01-05 21:05 UTC, zacharyfrederick approved these changes

2024-01-05 23:09 UTC, nathanwhit approved these changes
Left some comments. Nothing blocking, but stuff to maybe address in the future.

2024-01-05 23:18 UTC, merged

2024-01-08 09:35 UTC, atodorov commented on .github/authorized_keys
> +ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOYiBGthrSNqUJdN9h9PHzXQL8cP8gj5pP9LZDx7BVgt/Knm9NwAe9hD/7fs9zmyECmZ5ubHDqG0x7Hb7DAjl+oPkCOxqRj5Npfvl1VRwwgXl3ymfI3JJpF7Cna4n0XdylBsTiwOL1/zoVXEJgTYEDEsP4gv65i8M
Allows you to ssh into the self-hosted runner VM. This is my public ssh key.

2024-01-08 09:44 UTC, atodorov commented on Dockerfile
> +ENTRYPOINT [ "/bin/creditcoin-node" ]
+1 for keeping the name consistent everywhere. I think this is a left-over from when we weren't sure how to call it.

https://github.com/gluwa/creditcoin3/pull/160