[CSUB-1011] EVM Tracer to CC3
gluwa/creditcoin3 pull request #169
Opened 2024-01-12 17:29 UTC by frankli-dev

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-01-15 11:54 UTC, atodorov requested changes
Failing CI jobs need some more attention.

2024-01-15 11:54 UTC, atodorov commented on runtime/Cargo.toml
> +moonbeam-rpc-primitives-txpool = { workspace = true }
IMO we should add all of these Cargo.toml files into dependabot.yml in case there's ever a dependency which doesn't come from the workspace.

2024-01-16 17:40 UTC, atodorov requested changes

2024-01-16 17:40 UTC, atodorov commented on runtime/src/lib.rs
> +            #[cfg(feature = "evm-tracing")]
Question: is this going to be conditionally compiled or should be part of the regular build/docker image ? 

Maybe one option will be to remove the conditionals if we want to have this always enabled.

2024-01-16 17:40 UTC, atodorov commented on node/src/eth.rs
> +    + moonbeam_rpc_primitives_txpool::TxPoolRuntimeApi<Block>
These additional RPC calls would need some sort of integration test at the very minimum. 

Skeleton for running tests against blockchain added in https://github.com/gluwa/creditcoin3/pull/171, example RPC tests from Creditcoin2 -> https://github.com/gluwa/creditcoin/tree/dev/integration-tests/src/test/rpc

2024-01-16 22:34 UTC, nathanwhit reviewed
I haven't thoroughly reviewed all of the vendored code (it's a lot of code), but the changes here look how I expected them to. There are some unnecessary changes/vendored code, and we should probably rename some of the packages from `moonbeam-*` to `creditcoin3-*` but largely looks good.

2024-01-16 22:34 UTC, nathanwhit commented on node/cli-opt/src/lib.rs
> +    pub frontier_backend_config: FrontierBackendConfig,
Not needed

2024-01-16 22:34 UTC, nathanwhit commented on primitives/account/Cargo.toml
> +[package]
Crate not needed

2024-01-16 22:34 UTC, nathanwhit commented on primitives/core/Cargo.toml
> +[package]
Crate not needed

2024-01-16 22:40 UTC, nathanwhit commented on runtime/src/lib.rs
> +            #[cfg(feature = "evm-tracing")]
It is conditionally compiled, since according to moonbeam the tracing functionality has a _lot_ of overhead (in execution time and memory usage) - so not all nodes will run with it. Only some nodes (the ones used by blockscout, for instance) will use an image built with this flag.

2024-01-22 17:39 UTC, atodorov commented on node/src/eth.rs
> +    + moonbeam_rpc_primitives_txpool::TxPoolRuntimeApi<Block>
@nathanwhit https://github.com/gluwa/creditcoin3/tree/dev/cli/src/test/blockchain-tests is where blockchain tests live in this repo. The "integration-tests" directory is integration tests for the cli.

2024-01-22 23:31 UTC, zacharyfrederick submitted a review, later dismissed

2024-01-23 15:20 UTC, atodorov commented on cli/src/test/blockchain-tests/helpers.ts
> +export const deployContract = async (
CC @pLabarta FYI, you may be looking into this soon.

2024-01-23 15:25 UTC, frankli-dev commented
> Requested some changes, mainly around portability & readability of the newly added test.
> 
> The test logic itself looks good, however it fails with
> 
> ```
>     could not coalesce error (error={ "code": -32601, "message": "Method not found" }, payload={ "id": 59, "jsonrpc": "2.0", "method": "debug_traceTransaction"
> ```
> 
> See: [https://github.com/gluwa/creditcoin3/actions/runs/7627194788 /job/20776099144?pr=169](https://github.com/gluwa/creditcoin3/actions/runs/7627194788/job/20776099144?pr=169)
> 
> There are unresolved CI failures which need to be addressed.

I see why it's failing.
We should build the node with the additional flag.

```
--features=evm-tracing
```

Also, we should run the node with the additional flag.
```
--ethapi=debug,trace,txpool
```

@atodorov Could you please help me to add these to CI building & running stuff?

2024-01-23 17:45 UTC, atodorov commented on runtime/Cargo.toml
> +moonbeam-rpc-primitives-txpool = { workspace = true }
@frankli-dev, @nathanwhit do you want to address this one here or separately ?

2024-01-23 20:46 UTC, nathanwhit commented
Spoke with Dave and agreed we'll merge this today without the integration test, and open a follow-up PR with it. I'm going to just roll back the branch (force push) and re-open a PR with the test.

2024-01-23 20:48 UTC, merged