[CSUB-1013] Fix typo & create eraOption
gluwa/creditcoin3 pull request #172
Opened 2024-01-16 19:24 UTC by pLabarta

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-01-17 09:42 UTC, atodorov requested changes
2 warnings from eslint, otherwise looks good to me.

2024-01-17 09:42 UTC, atodorov commented on cli/src/commands/staking/distribute.ts
>  import { requireEnoughFundsToSend, signSendAndWatch } from '../../lib/tx';
See the warnings from the lint action.

2024-01-17 14:07 UTC, atodorov approved these changes

2024-01-20 04:09 UTC, nathanwhit approved these changes

2024-01-21 23:40 UTC, merged