[CSUB-957] Add convert-address command to CLI
gluwa/creditcoin3 pull request #173
Opened 2024-01-17 14:28 UTC by pLabarta

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-01-17 17:36 UTC, atodorov requested changes

2024-01-17 17:36 UTC, atodorov commented on cli/src/commands/options.ts
> +            throw new InvalidArgumentError('Not a valid Substrate or EVM address.');
Tryong out with Alice's address (copied from Polkadot JS Apps):


```
$ node dist/cli.js convert-address --address 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutY
error: option '--address [address]' argument '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutY' is invalid. Not a valid Substrate or EVM address.
```

2024-01-17 17:36 UTC, atodorov commented on cli/src/commands/options.ts
> +            throw new InvalidArgumentError('Not a valid Substrate or EVM address.');
One thing about these try-catch blocks is that they will switch control flow regardless of the actual exception which in some cases may be wrong. Preferably you will be catching only specific exceptions.

2024-01-17 17:36 UTC, atodorov commented on cli/src/cli.ts
> +    .addCommand(makeConvertAddressCommand())
Will need an integration test. Ideally Going from Substrate -> EVM  and EVM -> Substrate comparing against well known values, e.g. account which we already control and know their addresses so we can compare.

2024-01-17 17:36 UTC, atodorov commented on cli/src/commands/options.ts
> +            throw new InvalidArgumentError('Not a valid Substrate or EVM address.');
Going the other way around with an address I have from MetaMask seems to work: 

```
$ node dist/cli.js convert-address --address 0x90463393676f7206C829d6437f8B63b5800205c5
AssociatedSubstrate address: 5EmQmkyvmHNjneJsqSGvbapYDeVugCQ3jq68DA1yLfYwvXgC
```

2024-01-17 17:39 UTC, atodorov requested changes

2024-01-17 17:39 UTC, atodorov commented on cli/src/cli.ts
> +    .addCommand(makeConvertAddressCommand())
```
$ node dist/cli.js convert-address --address 0x90463393676f7206C829d6437f8B63b5800205c5
AssociatedSubstrate address: 5EmQmkyvmHNjneJsqSGvbapYDeVugCQ3jq68DA1yLfYwvXgC

$ node dist/cli.js convert-address --address 5EmQmkyvmHNjneJsqSGvbapYDeVugCQ3jq68DA1yLfYwvXgC
Associated EVM address: 0x77840434c2fc441634c90c0a935cafde65a42b13
```

We know that the conversion doesn't work in a circle. We need to add some warning inside the usage text on this command to indicate this. Otherwise it will lead to confusion.

2024-01-19 17:55 UTC, atodorov requested changes
Overal looks good, needs a few minor improvements to integration test.

2024-01-19 17:55 UTC, atodorov commented on cli/src/test/integration-tests/convertAddress.test.ts
> +        expect(result.stdout).toContain('0x');
Can you `expect().toEqual()` with the actual value so that we can find failures in case something does happen.

2024-01-19 17:55 UTC, atodorov commented on cli/src/test/integration-tests/convertAddress.test.ts
> +        expect(result.stdout).toContain('5');
Same here. Assert equal.

2024-01-19 17:55 UTC, atodorov commented on cli/src/test/integration-tests/convertAddress.test.ts
> +    // Test a known convertion from Substrate to EVM works
drop the comment b/c the string inside the `it()` function should be descritive enough not to need comments.

2024-01-19 17:55 UTC, atodorov commented on cli/src/test/integration-tests/convertAddress.test.ts
> +        expect(result.stderr).toContain('Not a valid Substrate or EVM address.');
Missing scenario for converting an invalid Substrate address.

2024-01-19 17:55 UTC, atodorov commented on cli/src/test/integration-tests/convertAddress.test.ts
> +        // Test that command fails with an invalid address
comment is redundant, but maybe the it() description can be more descriptive and say that the address is too short!

2024-01-19 17:55 UTC, atodorov commented on cli/src/test/integration-tests/convertAddress.test.ts
> +        expect(result.stdout).toContain('0x');
Essentially what you have in the last 2 test scenarios. So these first 2 scenarios are redundant.

2024-01-20 04:08 UTC, nathanwhit approved these changes

2024-01-22 09:45 UTC, atodorov approved these changes

2024-01-22 09:46 UTC, merged