CSUB-1012: Add proxy functionality to CLI
gluwa/creditcoin3 pull request #179
Opened 2024-01-21 18:55 UTC by zacharyfrederick

2024-01-21 23:46 UTC, pLabarta requested changes

2024-01-21 23:46 UTC, pLabarta commented on cli/src/cli.ts
> +    .addCommand(makeProxyCommands());
Could you keep the alphabetical order in the command list?

2024-01-21 23:46 UTC, pLabarta commented on cli/src/commands/options.ts
> +export function parseProxy(value: string): string {
You can reuse the Substrate address parsing func instead

2024-01-21 23:46 UTC, pLabarta commented on cli/src/commands/proxy/actions.ts
> +    const proxyAddr = parseSubstrateAddress(opts.proxy);
I think the Substrate address is already parsed & validated at this point, should not need to parse it again. Maybe casting it `as string`?

2024-01-21 23:46 UTC, pLabarta commented on cli/src/commands/proxy/types.ts
> +export const ProxyTypes = ['All', 'Staking', 'NonTransfer'];
Isn't the unrestricted proxy type called `Any` instead of All? https://github.com/polkadot-js/api/blob/747855b161fd6fad58c58cdaafbca407f903823d/packages/types-known/src/spec/polkadot.ts#L13

2024-01-21 23:46 UTC, pLabarta commented on cli/src/lib/staking/bond.ts
> +    if (proxy) {
It smells having CLI error handling code in the lib. Can it be solved rephrased or be checked at the CLI level?

2024-01-21 23:46 UTC, pLabarta commented on cli/src/lib/staking/validate.ts
> +        if (!address) {
Same comment about CLI error handling as with the bond command.

2024-01-21 23:46 UTC, pLabarta commented on cli/src/test/integration-tests/proxy.test.ts
> +async function randomFundedAccount(api: ApiPromise, sudoSigner: KeyringPair, amount: BN = parseAmount('1000')) {
Not a blocker, but would be better to include in and export these utils from the integration test `helpers`.

2024-01-22 10:13 UTC, atodorov commented on cli/src/commands/proxy/commands.ts
> +        .addOption(proxyTypeOption.choices(ProxyTypes).makeOptionMandatory())
Can the choices list be defined in options.ts where `proxyTypeOption` is defined instead of repeating it wherever it is used ? 

Similar for `.makeOptionMandatory()` b/c it looks like this option is always mandatory.

2024-01-22 10:13 UTC, atodorov commented on cli/src/commands/options.ts
> +export const delayOption = new Option('--delay [delay]', 'The delay for the proxy').argParser(parseProxyDelay);
I see that we need an integer value but what does this measure? Is it seconds or blocks, or something else? 

The option text could be improved to give more contextual information.

2024-01-22 10:13 UTC, atodorov commented on cli/src/commands/staking/distribute.ts
> +            console.log('ERROR: proxy keyring not provided through $PROXY_SECRET or interactive prompt');
Can we rename `PROXY_SECRET` to `CC_PROXY_SECRET` for consistency with the rest of the ENV variables?

2024-01-22 10:13 UTC, atodorov commented on cli/src/commands/staking/distribute.ts
> +        if (!proxy) {
How are the 2 if conditions supposed to work ? This is equivalent to `if X and !X` which is always False.

2024-01-22 10:13 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +    it.skip('Can successfully bond and unbond with a proxy account', async () => {
I propose a slightly different approach here. 

1) Use proxy.test.ts to exercise the add/list/remove functionality. Split that into discrete scenarios for more readability, etc

2) Instead of hand-picking which other scenarios to exercise IMO we can go the way of parametrized tests -> convert the `integration-test-cli` job in `ci.yml` into a matrix job which defines CC_PROXY_SECRET and then functions like `CLIBuilder` used in every integration test will decide whether to use proxy or not. Thus exercising every possible test that we have with and without a proxy configuration.

Let me know WDYT and I can help you out with this if necessary.

2024-01-22 16:41 UTC, zacharyfrederick commented on cli/src/commands/proxy/types.ts
> +export const ProxyTypes = ['All', 'Staking', 'NonTransfer'];
Hmm, that is interesting. Using polkadotjs I see only `All`, `Staking`, and `NonTransfer` as the options for our runtime.

2024-01-22 17:01 UTC, zacharyfrederick commented on cli/src/commands/staking/distribute.ts
> +        if (!proxy) {
Ah this is dead and should be removed

2024-01-22 17:07 UTC, atodorov commented on cli/src/commands/proxy/commands.ts
> +        .addOption(proxyTypeOption.choices(ProxyTypes).makeOptionMandatory())
I meant something like

```
export const proxyTypeOption = new Option('--type [type]', 'The type of proxy').choices(ProxyTypes).makeOptionMandatory();
```

2024-01-22 17:09 UTC, atodorov requested changes

2024-01-22 17:09 UTC, atodorov commented on cli/src/commands/staking/bond.ts
> +        console.log('ERROR: proxy keyring not provided through $PROXY_SECRET or interactive prompt');
Need to update log messages with the new variable name

2024-01-22 17:11 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +    it.skip('Can successfully bond and unbond with a proxy account', async () => {
> Should it be a follow-up ticket for the sake of getting this merged today?

If that's the only item left after code review then we can do it as a follow-up.

2024-01-22 17:14 UTC, atodorov commented on cli/src/commands/options.ts
> +export const ProxyTypes = ['All', 'Staking', 'NonTransfer'];
1. I saw a comment about possibly more proxy types being available. We need to figure out what's available and what isn't. 
2. What are the differences between the proxy types ? For exampe "NonTransfer" sounds like I cannot perform balances.Transfer transactions, however can I perform staking transactions? This isn't clear at all. At the very least needs some sort of documentation or a pointer (e.g. URL) to the differences.   Most likely will also need some sort of sanity tests to make sure we're handling errors gracefully.

2024-01-22 17:19 UTC, zacharyfrederick commented on cli/src/commands/proxy/commands.ts
> +        .addOption(proxyTypeOption.choices(ProxyTypes).makeOptionMandatory())
Ah I am dumb just pushed that change

2024-01-22 17:51 UTC, atodorov requested changes

2024-01-22 17:51 UTC, atodorov commented on cli/package.json
> +        "@polkadot/types-augment": "^10.11.2",
Binary file [cli/creditcoin3-v0.0.1.tgz](https://github.com/gluwa/creditcoin3/pull/179/files#diff-cd851367fa264b36d74500d0b8f9e5a7e0534de8be427105c30434a51a910d42) should be removed from git.

2024-01-22 21:14 UTC, nathanwhit reviewed
A few comments, not done reviewing

2024-01-22 22:00 UTC, zacharyfrederick commented on cli/src/commands/staking/bond.ts
>      const callerKeyring = await initCallerKeyring(options);
Yeah I went back and forth on that. I just pushed changes that return null from the init keyring if proxy is selected and added an --address flag to the staking commands

2024-01-22 22:01 UTC, zacharyfrederick commented on cli/src/commands/staking/bond.ts
>      const callerKeyring = await initCallerKeyring(options);
So everything makes a big more sense now

2024-01-23 02:26 UTC, nathanwhit reviewed
I would suggest a different approach than passing around both proxyKeyring and callerKeyrings which are both nullable, as it complicates the logic (and as Pablo noted it sort of spills over into the lib code).

Instead, I would suggest making a discriminated union that tells you whether it's a proxy or non-proxy, and carries around the proxied address.

more concretely, something like (names are all bad bc i suck at naming):

```ts
// in keyring.ts
export type ProxyKeyring = {
    type: 'proxy';
    pair: KeyringPair;
    proxiedAddress: string;
};

export type CallerKeyring = {
    type: 'caller';
    pair: KeyringPair;
};

export type CcKeyring = ProxyKeyring | CallerKeyring;

export async function initKeyring(options: OptionValues): Promise<CcKeyring> {
    try {
        if (options.proxy) {
            const pair = await initKeyringFromEnvOrPrompt('CC_PROXY_SECRET', 'proxy', options);
            if (!options.address) {
                throw new Error("ERROR: Address not supplied, provide with '--address <address>'");
            }
            return { type: 'proxy', pair, proxiedAddress: options.address };
        }
        const pair = await initKeyringFromEnvOrPrompt('CC_SECRET', 'caller', options);
        return { type: 'caller', pair };
    } catch (e) {
        console.error(getErrorMessage(e));
        process.exit(1);
    }
}
```

then have a helper function that wraps the transaction in a proxy call if it's a proxy keyring:

```ts
// in tx.ts
import { CcKeyring } from './account/keyring';

export async function signSendAndWatchCcKeyring(
    tx: SubmittableExtrinsic<'promise', ISubmittableResult>,
    api: ApiPromise,
    keyring: CcKeyring,
) {
    switch (keyring.type) {
        case 'caller':
            return await signSendAndWatch(tx, api, keyring.pair);
        case 'proxy': {
            const proxyTx = api.tx.proxy.proxy(keyring.proxiedAddress, null, tx.method);
            return await signSendAndWatch(proxyTx, api, keyring.pair);
        }
        default:
            const assertExhaustive = (_t: never) => {
                throw new Error(`Invalid keyring type`);
            };
            return assertExhaustive(keyring);
    }
}
```

Putting all that together, the `bond` function would look like

```ts
// in bond.ts
export async function bond(
    stashKeyring: CcKeyring,
    amount: BN,
    rewardDestination: RewardDestination,
    api: ApiPromise,
    extra = false,
) {
    console.log(`Amount: ${amount.toString()}`);

    if (BigInt(amount.toString()) < BigInt(MICROUNITS_PER_CTC)) {
        throw new Error('Amount to bond must be at least 1');
    }

    const amountInMicroUnits = amount;

    let bondTx: SubmittableExtrinsic<'promise', ISubmittableResult>;

    if (extra) {
        bondTx = api.tx.staking.bondExtra(amountInMicroUnits.toString());
    } else {
        bondTx = api.tx.staking.bond(amountInMicroUnits.toString(), rewardDestination);
    }

    await requireEnoughFundsToSend(bondTx, stashKeyring.pair.address, api, amount);
    return await signSendAndWatchCcKeyring(bondTx, api, stashKeyring);
}
```

That keeps the proxy stuff nice and encapsulated

2024-01-23 11:29 UTC, atodorov requested changes
Spotted more failures and/or issues which need to be address, still doing more in-depth testing. The issues observed will also require additional integration or unit tests. 

At this point this PR is getting too big and there are many moving parts. I propose splitting it out into chunks in the following order:

1. list command
2. add command
3. remove command
4. enabling other commands to use proxy.

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/options.ts
> +}
Input validation doesn't seem to work (will require tests): 

Using decimal dot:

```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All --delay "0.2"
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x7e870dd08610f56c4910f81ee9f1479348da1350ada25374ae5bf9e0a0138d90'
}
```

After removing it, try again using a decimal comma:

```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All --delay "0,2"
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0xf9398a0ad724e3be0684ffa56fa46b1c66be291a8de00d0d219735552d95f636'
}
```

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/options.ts
> +}
Failed as expected for negative values:

```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All --delay "\-2"
/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:533
      throw err;
      ^

Error: ERROR: Could not parse delay: \-2
    at Option.parseProxyDelay [as parseArg] (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/commands/options.js:111:15)
    at Command._callParseArg (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:527:21)
    at handleOptionValue (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:572:20)
    at Command.<anonymous> (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:592:7)
    at Command.emit (node:events:518:28)
    at Command.parseOptions (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:1474:18)
    at Command._parseCommand (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:1256:25)
    at /home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:1082:27
    at Command._chainOrCall (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:1193:12)
    at Command._dispatchSubcommand (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/commander/lib/command.js:1078:25)

Node.js v20.11.0
```

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +        console.log(`ERROR: No proxies has been set for ${callerAddress}`);
Typo:

```suggestion
        console.log(`ERROR: No proxies have been set for ${callerAddress}`);
```

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    }
When I don't have any proxies configured for the caller account error handling works as expected:

```
$ node dist/cli.js proxy remove -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All --delay "0"
ERROR: No proxies has been set for 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
```

Then I add a proxy account:

```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x0f4778b74f55357c956bae6283a3abf7d891ad641f3323d106af18a8e7cf5311'
}
```

and try to remove a proxy which doesn't use the address I've added (using ALICE in this example):

```
[gluwa@fedora cli]$ node dist/cli.js proxy remove -p 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY --type All --delay "0"
Sending transaction...
{
  status: 1,
  info: 'Transaction failed with error: "proxy.NotFound: Proxy registration not found." at block 0x58566ce8b6347fd6fb43f8bc64dea5b81b5c7e05318e90ef950c16866428cad1'
}
```

I was expecting a nice error handling here as well.

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    }
Trying to remove with the correct address but using the wrong type also isn't handled gracefully:

```
$ node dist/cli.js proxy remove -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type NonTransfer
Sending transaction...
{
  status: 1,
  info: 'Transaction failed with error: "proxy.NotFound: Proxy registration not found." at block 0x483b329d29ae89d570ae84dd15e7ffb54662ed3642f9492a276070871ced5aac'
}
```

Do we really need the user to specify `--type` here ?  I feel like it's better that we match by proxy address and reuse the type which was already configured. WDYT?

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +export async function setProxyAction(opts: OptionValues) {
Apparently I can configure proxy with the same address multiple times using a different `--type`: 


```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0xd2eaafc165d973c2d988049a813be35e7e63b8d915f54bc3f6de302fae854a72'
}

$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type NonTransfer
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x86c8f13ed3cef625a2a2b1d65fd3b4cf763091e79acfd06a1f361379c27e8f71'
}

$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type Staking
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0xc465ef3e12f14568629248b9ae59a55043bd0fa24e0158ad9df535b1e5af4f1d'
}
```

I'm still uncertain how that impacts behavior. For example Staking & NonTransfer types appear to be mutually exclusive. Does this mean both staking and balances.Transfer actions will be allowed in this case?

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +export async function setProxyAction(opts: OptionValues) {
For good measure tried adding the same address + type combo once again

```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type NonTransfer
Sending transaction...
{
  status: 1,
  info: 'Transaction failed with error: "proxy.Duplicate: Account is already a proxy." at block 0xe77690078aa281a4fad724c5d14e35b982b5162eeaa288c81475386806419bf7'
}
```

and this time it failed as expected.

2024-01-23 11:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    process.exit(0);
This should really be  `process.exit(result.status)` to exit with a non-zero code when transactions fail. Otherwise makes the cli commands harder to use in scripts:


```
$ node dist/cli.js proxy add -p 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type NonTransfer
Sending transaction...
{
  status: 1,
  info: 'Transaction failed with error: "proxy.Duplicate: Account is already a proxy." at block 0xe77690078aa281a4fad724c5d14e35b982b5162eeaa288c81475386806419bf7'
}

$ echo $?
0
```


Note: this seems to be an issue everywhere. I will open a ticket for it.

2024-01-23 12:13 UTC, atodorov commented on cli/src/commands/staking/distribute.ts
> +    }
Even after specifying all of the necessary arguments I get a failure:

```
$ node dist/cli.js distribute-rewards -u ws://127.0.0.1:9955 --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp --era 324 --substrate-address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
✔ Specify a seed phrase for the proxy account … ***********************************************************************
/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/commands/staking/distribute.js:41
        throw new Error('ERROR: keyring not initialized and proxy not selected');
              ^

Error: ERROR: keyring not initialized and proxy not selected
    at Command.distributeRewardsAction (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/commands/staking/distribute.js:41:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.0
```

Here I am trying to distribute rewards earned only by myself.

2024-01-23 12:17 UTC, atodorov commented on cli/src/commands/staking/chill.ts
Error when trying to use a secret which is not the proxy account secret:

```
$ node dist/cli.js chill -u ws://127.0.0.1:9955 --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
✔ Specify a seed phrase for the proxy account … **********************************************************************
ERROR: Status was undefined
```

In other commands if I try doing this I get 
```
Transaction failed with error: "proxy.NotProxy: Sender is not a proxy of the account to be proxied." at block 0x39b4808b97758fd37031aac511be017366ba8de5e31b45977255ada1785c1b2d
```

2024-01-23 12:18 UTC, atodorov commented on cli/src/commands/staking/chill.ts
I get the same `Status is undefined` error even when supplying the correct secret for the proxy account!

2024-01-23 12:33 UTC, atodorov commented on cli/src/commands/staking/unbond.ts
> +    const proxy = await initProxyKeyring(options);
looks like a left-over because in other commands which have the `--proxy` and `--address` options this isn't required.

2024-01-23 12:36 UTC, atodorov commented on cli/src/commands/staking/unbond.ts
> +    const status = await getValidatorStatus(caller?.address, api);
Shouldn't this be `options.address` ?

2024-01-23 12:36 UTC, atodorov commented on cli/src/commands/staking/unbond.ts
> +    await checkIfUnbodingMax(caller?.address, amount, api, interactive);
`options.address` ?

2024-01-23 12:57 UTC, atodorov commented on cli/src/commands/staking/withdraw.ts
> +    const result = await signSendAndWatch(withdrawUnbondTx, api, callerKeyring);
All unbonded funds are already unlocked, then:


Trying out with a secret which IS NOT the configured proxy account:

```
$ node dist/cli.js withdraw-unbonded -u ws://127.0.0.1:9955 --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp 
✔ Specify a seed phrase for the proxy account … *******************************************************************************
Cannot perform action, there are no unlocked funds to withdraw
```

I was expecting `proxy.NotProxy` error here.

Using the correct secret for the proxy account results in a successfull transaction.

2024-01-23 12:58 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +        expect(test1Res.stdout).toContain('[ [], 0 ]'); // Indicates no proxies have been set and 0 funds have been proxied
Note: I was wondering what that `0` was. 

We probably want to update the `list` command and make the display a bit more verbose.

2024-01-24 10:50 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    }
Works with exported secret:

```
$ export CC_SECRET="twice wash veteran endorse water orbit fit casino flame provide cancel peace"
$ node dist/cli.js proxy list 
Proxies for address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
[
  [
    {
      delegate: '5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa',
      proxyType: 'All',
      delay: 0
    }
  ],
  1000
]
```


Also works when secret isn't set in ENV and asks for it interactively.

```
$ unset CC_SECRET
$ node dist/cli.js proxy list 
✔ Specify a seed phrase for the caller account … ****************************************************************************
Proxies for address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
[
  [
    {
      delegate: '5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa',
      proxyType: 'All',
      delay: 0
    }
  ],
  1000
]
```

2024-01-24 11:02 UTC, atodorov commented on cli/src/commands/proxy/commands.ts
> +        .addOption(urlOption)
The `--url` option for any of these commands is not respected. 

If I leave a node running at port `:9955` and specify it's URL on the command line all of the commands are still trying to connect to the default address on port `:9944`:

```
$ node dist/cli.js proxy list -u ws://127.0.0.1:9955
2024-01-24 12:57:12          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:57:14          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:57:17          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:57:19          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure



$ node dist/cli.js proxy add -u ws://127.0.0.1:9955 --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type All
2024-01-24 12:58:44          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:58:46          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:58:49          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure


$ node dist/cli.js proxy remove -u ws://127.0.0.1:9955 --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa
2024-01-24 12:59:03          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:59:06          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
2024-01-24 12:59:08          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure

```

2024-01-24 11:02 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    const { api } = await newApi(opts.url);
Now asking for passphrase on the command line:

```
$ node dist/cli.js proxy remove --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa
✔ Specify a seed phrase for the caller account … ****************************************************************************
1 proxies found
Removing proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa with type All}
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x5e113064623fb30a61ae3133fea4b3792015a08137a4c3ed527ecefff919ef26'
}
1 Proxies removed
```

2024-01-24 11:11 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +        console.log(`Removing proxy ${proxy} with type ${type}}`)
Extra trailing `}`

```suggestion
        console.log(`Removing proxy ${proxy} with type ${type}`)
```

2024-01-24 11:11 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    }
Trying to remove a proxy account which doesn't match the one configured now handles the error as expected:

```
$ node dist/cli.js proxy remove --proxy 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
✔ Specify a seed phrase for the caller account … ****************************************************************************
ERROR: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY is not a proxy for 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
```


> Trying to remove with the correct address but using the wrong type

This is not an issue anymore because all types matching the address are removed.

2024-01-24 12:05 UTC, atodorov commented on cli/src/commands/staking/bond.ts
>      await checkBalance(amount, api, callerAddress);
Still doesn't work as expected b/c `stashKeyring.pair.address` defaults to the proxy address when a proxy is in use:

Address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp has over 100k CTC:
![image](https://github.com/gluwa/creditcoin3/assets/1002300/27efcf90-cfe3-4d4f-b716-75153d4756fa)

while the error message is showing me funds for the proxy account:
![image](https://github.com/gluwa/creditcoin3/assets/1002300/447569da-bb7d-474e-879e-4d8995e775d9)


```
node dist/cli.js bond -u ws://127.0.0.1:9955 --amount 100000 -r Stash --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
✔ Specify a seed phrase for the proxy account … ***********************************************************************
Insufficient funds to bond 100000.000000000000000000 CTC, only 1109.685750678926592250 CTC available
```

2024-01-24 12:05 UTC, atodorov commented on cli/src/commands/staking/setKeys.ts
> +    }
There is still no `--proxy` option here!

2024-01-24 12:20 UTC, atodorov commented on cli/src/lib/account/keyring.ts
> +}
This function isn't used anywhere, anymore. Please remove.

2024-01-24 12:20 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    const callerKeyring = await initCallerKeyring(opts, true);
All of the add/remove/list actions are signed by the caller account, not by the proxy account, so we don't need the `, true)` parameter and the possibility that `initCallerKeyring` can return `null` IMO.

2024-01-24 12:20 UTC, atodorov commented on cli/src/commands/staking/distribute.ts
>      process.exit(0);
While we're at it: 

```suggestion
    process.exit(result.status);
```

2024-01-24 12:20 UTC, atodorov commented on cli/src/commands/staking/unbond.ts
>      process.exit(0);
While we're at it: 

```suggestion
    process.exit(result.status);
```

2024-01-24 12:20 UTC, atodorov commented on cli/src/commands/staking/withdraw.ts
>      process.exit(0);
While we're at it: 

```suggestion
    process.exit(result.status);
```

2024-01-24 12:20 UTC, atodorov commented on cli/src/commands/staking/distribute.ts
> +    }
Worked this time around!

2024-01-24 12:23 UTC, atodorov commented on cli/src/commands/staking/chill.ts
Now, regardless of whether I use the secret for the proxy account or for a different account I get a different error, but still the `chill` action doesn't work as expected:

```
node dist/cli.js chill -u ws://127.0.0.1:9955 --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
✔ Specify a seed phrase for the proxy account … ***********************************************************************
Cannot perform action, validator is not validating
```

The validator is indeed active and is generating rewards!

2024-01-24 13:02 UTC, atodorov commented on cli/src/commands/staking/withdraw.ts
> +    const status = await getValidatorStatus(keyring.pair.address, api);
This is the status for the proxy account! See my comment above for the `validatorAddress` helper function.

2024-01-24 13:02 UTC, atodorov commented on cli/src/commands/staking/withdraw.ts
> +    const result = await signSendAndWatch(withdrawUnbondTx, api, callerKeyring);
Now, after all unbonded funds have been unlocked I get the same error `Cannot perform action, there are no unlocked funds to withdraw` regardless if I use the correct proxy secret or not. Before when using the correct proxy secret it used to work.

2024-01-24 13:05 UTC, atodorov requested changes
Did another round of review after recent changes and resolved/unresolved previous conversations according to status.

2024-01-24 13:17 UTC, atodorov commented on cli/src/commands/staking/unbond.ts
> +    const validator_addr = caller.type === 'proxy' ? caller.proxiedAddress : caller.pair.address;
Actually IMO it's better of this is a function or property of the `CcKeyring` type so we can call it directly where needed.

2024-01-24 13:28 UTC, atodorov requested changes

2024-01-24 13:28 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +        const test2Res = CLI(`bond --amount 1 --proxy --address ${caller.address}`);
Error handling for `signSendAndWatch()` function needs to be updated to account for dispatch errors from proxy calls!

2024-01-25 14:26 UTC, atodorov requested changes

2024-01-25 17:58 UTC, atodorov commented on cli/src/commands/options.ts
> +).argParser(parseProxyDelay);
Options have a `.default()` method, see for example:
```
export const urlOption = new Option('-u, --url [url]', 'URL of the node to connect to').default('ws://127.0.0.1:9944');
```

Using a `.default(0)`  should resolve https://github.com/gluwa/creditcoin3/pull/179#discussion_r1466281272 and also render https://github.com/gluwa/creditcoin3/pull/179/files#diff-52866f33d90a325e71f67b8620e0f52cce0598363bee23b5b88f2a66fad663a6R7, `    const delay = opts.delay ? opts.delay : 0;` obsolete.

2024-01-25 18:02 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    const { api } = await newApi(options.url as string);
This is the pattern used everywhere else in the source code. Exception is `setProxyAction` which doesn't cast the value coming from `parseSetProxyOptions` as a string and `removeProxyAction` which uses `options.url` directly, without casting it to string.

2024-01-25 18:03 UTC, atodorov commented on cli/src/commands/options.ts
> +).argParser(parseProxyDelay);
In fact imlementing the change above will also render the entire `parseSetProxyOptions` function obsolete.

2024-01-25 18:12 UTC, atodorov commented on cli/src/commands/proxy/commands.ts
> +        .addOption(urlOption)
I tried debugging with the following change

```diff
[gluwa@fedora src]$ git diff
diff --git a/cli/src/commands/proxy/actions.ts b/cli/src/commands/proxy/actions.ts
index 3186683..e335642 100644
--- a/cli/src/commands/proxy/actions.ts
+++ b/cli/src/commands/proxy/actions.ts
@@ -19,6 +19,8 @@ export async function setProxyAction(options: OptionValues) {
 }
 
 export async function viewProxyAction(options: OptionValues) {
+    console.log(`*** DEBUG viewProxyAction, options=${options}, url=${options.url}`);
+
     const { api } = await newApi(options.url as string);
 
     const callerKeyring = await initCallerKeyring(options);
diff --git a/cli/src/commands/staking/bond.ts b/cli/src/commands/staking/bond.ts
index 844d361..f9a0883 100644
--- a/cli/src/commands/staking/bond.ts
+++ b/cli/src/commands/staking/bond.ts
@@ -24,6 +24,7 @@ export function makeBondCommand() {
 }
 
 async function bondAction(options: OptionValues) {
+    console.log(`*** DEBUG bondAction, options=${options}, url=${options.url}`);
     const { api } = await newApi(options.url as string);
 
     const { amount, rewardDestination, extra, interactive } = parseOptions(options);
```


and the results came out not what I though:

```bash
$ node dist/cli.js proxy list --url ws://127.0.0.1:9966/
*** DEBUG viewProxyAction, options=[object Object], url=ws://127.0.0.1:9944
2024-01-25 20:08:34          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
^C



[gluwa@fedora cli]$ node dist/cli.js bond --url ws://127.0.0.1:9966/ --amount 10
*** DEBUG bondAction, options=[object Object], url=ws://127.0.0.1:9966/
✖ Specify a seed phrase for the caller account …
```

Here we can clearly see that the value for the `--url` argument is not respected at all. And my theory is because of the redundant definition of `--url` on the `proxy` command itself.

2024-01-25 18:14 UTC, atodorov commented on cli/src/commands/proxy/commands.ts
> +        .addOption(urlOption)
@zacharyfrederick see my previous comment. Just confirmed that applying the change suggested in https://github.com/gluwa/creditcoin3/pull/179#discussion_r1466290747 fixes this!

2024-01-26 10:01 UTC, atodorov commented on cli/src/commands/proxy/commands.ts
> +        .addOption(urlOption)
Works now.

2024-01-26 10:12 UTC, atodorov commented on cli/src/commands/staking/bond.ts
> +    cmd.option('-a, --address [proxy addr]', 'The address that is being proxied', parseSubstrateAddress);
These 2 options are used in multiple places. They should better be defined in `commands/options.ts` instead of being copy-pasted everywhere.

2024-01-26 10:12 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +        const delay = options.delay ? options.delay : 0;
Still needs to be updated.

2024-01-26 10:25 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +    console.log(success);
This is still a problem. 

TL;DR; when there is a proxy account added with the `--delay` option removal fails for it:

```

### Add proxy with --delay 2

$ node dist/cli.js proxy add --url ws://127.0.0.1:9955  --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --delay 2 --type All
✔ Specify a seed phrase for the caller account … ****************************************************************************
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x28606e68c3abf1cfc39e0cd81f6cf99171e0c690bf13d84fbc349c9f8543667e'
}


### Add a regular proxy w/o delay


$ node dist/cli.js proxy add --url ws://127.0.0.1:9955  --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type NonTransfer
✔ Specify a seed phrase for the caller account … ****************************************************************************
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x4b5107d966a629d7175f3467f527ba006765770812a7dd2edf041edca25306fa'
}


### Both are listed as expected

$ node dist/cli.js proxy list --url ws://127.0.0.1:9955 
{ input: true, url: 'ws://127.0.0.1:9955' }
✔ Specify a seed phrase for the caller account … ****************************************************************************
Proxies for address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
[
  [
    {
      delegate: '5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa',
      proxyType: 'All',
      delay: 2
    },
    {
      delegate: '5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa',
      proxyType: 'NonTransfer',
      delay: 0
    }
  ],
  1500
]

### Try removing them: 

$ node dist/cli.js proxy remove --url ws://127.0.0.1:9955  --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa 
✔ Specify a seed phrase for the caller account … ****************************************************************************
2 proxies found
Removing proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa with type All
Sending transaction...
{
  status: 1,
  info: 'Transaction failed with error: "proxy.NotFound: Proxy registration not found." at block 0xab2d7b065730f601dfbec9ca7282c6cce950dedd460b4ad45625d512ea14f453'
}
Removing proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa with type NonTransfer
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x15adcab28f4a17a40c880859bcaf98cbb452d028c92f344728d25ff695f13835'
}
2 proxies removed
[
  '{"delegate":"5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa","proxyType":"All","delay":2}',
  '{"delegate":"5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa","proxyType":"NonTransfer","delay":0}'
]

$ echo $?
0


#### ERRORS OUT:


### We can still see that the proxy specified with a delay is there. 

$ node dist/cli.js proxy list --url ws://127.0.0.1:9955 
{ input: true, url: 'ws://127.0.0.1:9955' }
✔ Specify a seed phrase for the caller account … ****************************************************************************
Proxies for address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
[
  [
    {
      delegate: '5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa',
      proxyType: 'All',
      delay: 2
    }
  ],
  1000
]
```




1) We get a message that there were 2 successfull removals and the overall exit status is zero. This means the error handling logic inside `removePorxyAction` doesn't work. I will comment in-line as to what I think is the problem.

2) Still unsure what causes the failure to remove a proxy with `--delay > 0`.

2024-01-26 12:28 UTC, atodorov requested changes
Reviewed and posted comments where necessary. The critical bits are:

* PR still needs rebase & conflict resolution
* `wizard` command doesn't work with a proxy
* `chill` command doesn't work with a proxy -> `Cannot perform action, validator is not validating`
* `proxy remove` command errors out when removing proxies that have `delay > 0`
* Input validation for the `--delay` option happily accepts values like "0,2" and "2.3" when in reality it is supposed to accept only integers

The rest of the comments are suggestions for code improvements which will increase readability and reduce confusion & repeating of common code snippets.

2024-01-26 12:28 UTC, atodorov commented on cli/src/commands/evm/fund.ts
> +    const result = await signSendAndWatchCcKeyring(tx, api, caller);
Trying to fund the associated EVM address of the proxied account when using a proxy of type "NonTransfer" failed but the failure wasn't handled in `signSendAndWatchCcKeyring()`: 

```
$ node dist/cli.js evm fund --url ws://127.0.0.1:9955  --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp --amount 4444 --evm-address 0x602b4159e30c760778d68b445140e5e560da8fe4 
{
  input: true,
  url: 'ws://127.0.0.1:9955',
  proxy: true,
  address: '5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp',
  amount: <BN: f0e8e396adcbf00000>,
  evmAddress: '0x602b4159e30c760778d68b445140e5e560da8fe4'
}
Funding EVM address 0x602b4159e30c760778d68b445140e5e560da8fe4 with 4444.000000000000000000 CTC
Sending to associated Substrate address 5EVpLwwjVbbmtprSbK1qMc9E6RL6LpsGcheotLdx9tkXMwPr
✔ Specify a seed phrase for the proxy account … ***********************************************************************
Sending transaction...
Transaction included at blockHash 0x700a684a91e3780c1f62107721abf3049a41bd8afbbcde0690a8b66c1b884e1b
```

![image](https://github.com/gluwa/creditcoin3/assets/1002300/b4c5400b-2cf4-420e-b579-d2217fa3a403)

2024-01-26 12:28 UTC, atodorov commented on cli/src/commands/evm/fund.ts
>      process.exit(0);
While we're at it:

```suggestion
    process.exit(result.status);
```

2024-01-26 12:28 UTC, atodorov commented on cli/src/commands/evm/withdraw.ts
> +    const caller = await initKeyring(options);
Hold up.  Keyring initialization is assuming that we can use a proxy here, but this command doesn't specify the `--proxy` and `--address` options. 

Without adding the proxy & address options the rest of the changes are not very useful. They could still stay I guess.

2024-01-26 12:28 UTC, atodorov commented on cli/src/commands/evm/withdraw.ts
> +    const evmAddress = substrateAddressToEvmAddress(caller.pair.address);
This is again either the caller address if not using a proxy (correct in the current implementation) or the proxiedAddress when `--proxy` option is added, which will make this line to be incorrect).  Yet another case in favor of encapsulating the proxy/non-proxy logic into a property as proposed in 
https://github.com/gluwa/creditcoin3/pull/179#discussion_r1464839591

2024-01-26 12:28 UTC, atodorov commented on cli/src/commands/evm/withdraw.ts
>  async function evmWithdrawAction(options: OptionValues) {
This is still going to suffer from the permission filtering error because calling EVM extrinsics are only possible with a proxy type of `All`.

2024-01-26 13:20 UTC, atodorov commented on cli/src/commands/options.ts
> +}
Inout validation & more tests fixed in https://github.com/gluwa/creditcoin3/pull/182

2024-01-26 17:06 UTC, atodorov requested changes

2024-01-26 17:06 UTC, atodorov commented on cli/src/commands/staking/setKeys.ts
> +    cmd.option('-a, --address [proxy addr]', 'The address that is being proxied', parseSubstrateAddress);
Error `session.NoAssociatedValidatorId`  with proxy type `NonTransfer` or `Staking`. I guess `ProxyFilter` in the runtime needs to be updated as well.

![image](https://github.com/gluwa/creditcoin3/assets/1002300/6d6f71f3-cc5c-4ed0-ae4e-c73890239ee2)

```
$ node dist/cli.js proxy add --url ws://127.0.0.1:9955 --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa --type NonTransfer
✔ Specify a seed phrase for the caller account … ****************************************************************************
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0xb3926aac980e04c2026cd111812d3f11d6c6af2322cc258ae9c36f6376b7380b'
}

$ node dist/cli.js set-keys --url ws://127.0.0.1:9955  --proxy --address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp --rotate
✔ Specify a seed phrase for the proxy account … ***********************************************************************
Sending transaction...
Transaction included at blockHash 0x56f6222d6d5d1176b9d8d8eaf34ce6cc6fc9d9036eda97104e70b71e9884eae5
```

2024-01-29 14:04 UTC, atodorov requested changes
* needs proper rebase
* failing CI jobs need addressing
* other comments are in-line

2024-01-29 14:04 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +    it.skip('Can list, add, and remove proxies for an account', async () => {
Why was this skipped in the latest commit ? 

From the latest job execution I see 1 failing + 3 skipped scenarios:
```
FAIL src/test/integration-tests/proxy.test.ts (61.067 s)
  Proxy functionality
    ✕ Can successfully validate and chill with a proxy account (60504 ms)
    ○ skipped Can list, add, and remove proxies for an account
    ○ skipped Can successfully bond and unbond with a proxy account
    ○ skipped Can successfully send funds with a proxy
```

while the test job for the previous commit, https://github.com/gluwa/creditcoin3/actions/runs/7659787358/job/20876171030, appears to have been better - 3 passing + 1 skipped scenarios:
```
PASS src/test/integration-tests/proxy.test.ts (224.358 s)
  Proxy functionality
    ✓ Can list, add, and remove proxies for an account (60439 ms)
    ✓ Can successfully bond and unbond with a proxy account (103333 ms)
    ✓ Can successfully send funds with a proxy (60021 ms)
    ○ skipped Can successfully validate and chill with a proxy account
```

2024-01-30 11:48 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +    it.skip('Can list, add, and remove proxies for an account', async () => {
Latest test execution at https://github.com/gluwa/creditcoin3/actions/runs/7700633719/job/20986051887?pr=179, reports PASS and looks good: 

```
PASS src/test/integration-tests/proxy.test.ts (315.053 s)
  Proxy functionality
    ✓ Can list, add, and remove proxies for an account (60430 ms)
    ✓ Can successfully bond and unbond with a proxy account (103329 ms)
    ✓ Can successfully validate and chill with a proxy account (90699 ms)
    ✓ Can successfully send funds with a proxy (60021 ms)
```

2024-01-30 16:15 UTC, pLabarta commented
Wizard command should be working properly now. Staking proxies do not have permissions to `bond` (only to `bond-extra`). Updated Wizard now makes bonding optional and warns the user for both proxy usage and when skipping bonding step for regular stash calls.

When  reviewing, read the warnings and let us know if they are not clear enough.

2024-01-30 18:44 UTC, atodorov commented on cli/src/commands/evm/fund.ts
> +import { amountOption, evmAddressOption, useProxyOption } from '../options';
unused import

2024-01-30 18:44 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +        const test2Res = CLI(`bond --amount 1 --proxy --address ${caller.address}`);
Still relevant!

2024-01-30 19:29 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +            success.push(p.toString());
This needs to be retested again with several proxies defined in such a way which would make `signSendAndWatch()` fail in the middle of the for loop to see if there will be an exception or `result.status > 0`  .

The only reasonable idea I get ATM is to have a proxy with very low funds so that it is incapable to pay fees after several iterations. I will give this a try tomorrow.

2024-01-30 19:29 UTC, atodorov commented on cli/src/commands/send.ts
> +        if (delegates.toArray().find((delegate) => delegate.proxyType.toString() === 'All') === undefined) {
See the filter at https://github.com/gluwa/creditcoin3/pull/179/files#diff-1d76b03c0657635340e119d4b4f7e34f35f4d5055f068e642d94ee3db19d8711R51

without this filter what happens is that: 

1) I use a secret for an account which has 0 funds and I expect `Inability to pay some fees` error which I get everywhere else, instead I get the error below
2) I use a secret for an account which does have funds but is not the proxy account and I expect `proxy.NotProxy` error as in everywhere else but I get this one instead.

2024-01-30 19:29 UTC, atodorov commented on cli/src/commands/send.ts
> +        if (delegates.toArray().find((delegate) => delegate.proxyType.toString() === 'All') === undefined) {
Probably a good idea to make the query and the filtering operation as seen in `actions.ts` into a helper function and use it where needed. Something like `proxiesForAddress()`.

2024-01-30 19:29 UTC, atodorov commented on cli/src/commands/staking/wizard.ts
> +        const bondExtra: boolean = keyring.type === 'proxy' ? true : checkIfAlreadyBonded(stashBalance);
This is still happening in exactly the same way!

2024-02-02 21:22 UTC, nathanwhit approved these changes
Two tiny style things but nothing blocking, it LGTM

2024-02-02 21:22 UTC, nathanwhit commented on cli/src/commands/staking/bond.ts
> +    checkAmount(options.amount as BN);
Don't really get this change

2024-02-02 21:22 UTC, nathanwhit commented on cli/src/commands/staking/unbond.ts
> +    const validator_addr = validatorAddress(caller);
```suggestion
    const validatorAddr = validatorAddress(caller);
```

2024-02-05 13:39 UTC, atodorov commented on cli/src/commands/staking/bond.ts
> +    checkAmount(options.amount as BN);
Probably a left-over from trying to revert this https://github.com/gluwa/creditcoin3/pull/179#discussion_r1469394082

2024-02-05 13:39 UTC, atodorov commented on cli/src/commands/staking/wizard.ts
> +        const bondExtra: boolean = keyring.type === 'proxy' ? true : checkIfAlreadyBonded(stashBalance);
Still happening!

2024-02-05 13:44 UTC, atodorov commented on cli/src/test/integration-tests/proxy.test.ts
> +        const test2Res = CLI(`bond --amount 1 --proxy --address ${caller.address}`);
Fixed

```
$ node dist/cli.js distribute-rewards -u ws://127.0.0.1:9966 --use-proxy 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp --era 16 --substrate-address 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY 
✔ Specify a seed phrase for the proxy account … ***********************************************************************
Sending transaction...
Proxy Transaction failed: staking.AlreadyClaimed: Rewards for this era have already been claimed for this validator.

$ echo $?
1
```

2024-02-05 14:57 UTC, atodorov requested changes

2024-02-05 14:57 UTC, atodorov commented on cli/src/commands/proxy/actions.ts
> +            success.push(p.toString());
Saved by the check on line 71:

```
$ node dist/cli.js balance --substrate-address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp -u ws://127.0.0.1:9966 
Address: 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
┌──────────────┬────────────┐
│ Transferable │ 0.0900 CTC │
├──────────────┼────────────┤
│ Locked       │ 0.0000 CTC │
├──────────────┼────────────┤
│ Bonded       │ 0.0000 CTC │
├──────────────┼────────────┤
│ EVM          │ 0.0000 CTC │
├──────────────┼────────────┤
│ Unbonding    │ 0.0000 CTC │
├──────────────┼────────────┤
│ Total        │ 0.0900 CTC │
└──────────────┴────────────┘
[gluwa@fedora cli]$ node dist/cli.js proxy remove -u ws://127.0.0.1:9966 --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa twice wash veteran endorse water orbit fit casino flame provide cancel peace
✖ Specify a seed phrase for the caller account … 
Error: Could not retrieve seed phrase


$ node dist/cli.js proxy remove -u ws://127.0.0.1:9966 --proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa
✔ Specify a seed phrase for the caller account … ****************************************************************************
3 proxies found
Removing proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa with type All
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x9e671ece83ab3b6b394fe05196bff9bafe449268c2798fcfea4d1fd77677af6a'
}
Removing proxy 5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa with type NonTransfer
Sending transaction...
{
  status: 0,
  info: 'Transaction included at blockHash 0x70b527a2da70fc253d0d43ecf934440dbd1dbea45a4dd5205bd74d4915548bfb'
}
Caller 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp has insufficient funds to send the transaction (requires 0.031632508557663006 CTC); transaction cancelled.

$ echo $?
1

$ node dist/cli.js proxy list -u ws://127.0.0.1:9966 
✔ Specify a seed phrase for the caller account … ****************************************************************************
Proxies for address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
{"delegate":"5HK5d9bNMcofBSGjKHqs8AChftaJBQ3rCLBxqnWZpc25uGKa","proxyType":"Staking","delay":0}
```

2024-02-05 19:46 UTC, nathanwhit submitted a review, later dismissed
One question (basically the same as Alex's question about the interaction between proxy and bonding) but LGTM

2024-02-05 20:48 UTC, merged