Tracing rpc tests
gluwa/creditcoin3 pull request #182
Opened 2024-01-23 20:49 UTC by nathanwhit

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-01-24 08:28 UTC, atodorov requested changes
@frankli-dev, @nathanwhit code review from https://github.com/gluwa/creditcoin3/pull/169#pullrequestreview-1839032848 still holds true. 

Additionally these 2 commits can be squashed together.

2024-01-24 08:37 UTC, atodorov requested changes
@frankli-dev additionally this comment on the original PR is also unresolved https://github.com/gluwa/creditcoin3/pull/169#discussion_r1452283533. Please resolve it.

2024-01-25 10:52 UTC, atodorov requested changes
Some changes requested

2024-01-25 10:52 UTC, atodorov commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        provider = new WebSocketProvider(ALICE_NODE_URL);
Use `(global as any).CREDITCOIN_API_URL` b/c these tests get executed against multiple different targets which is controlled via configuration files. The variable `ALICE_NODE_URL` is still a hard-coded value. 

See https://github.com/gluwa/creditcoin3/blob/dev/cli/src/test/blockchain-tests/danger-will-brick-the-blockchain.test.ts#L8C29-L8C63

2024-01-25 10:52 UTC, atodorov commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        const alith = new ethers.Wallet('0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133').connect(
Hard-coded value should not be used. 

Should use `createSigner('lender')` to create a known Substrate address:
https://github.com/gluwa/creditcoin3/blob/dev/cli/src/test/blockchainSetup.ts#L4

and then `substrateAddressToEvmAddress()` to get the associated EVM address:
https://github.com/gluwa/creditcoin3/blob/dev/cli/src/lib/evm/address.ts#L12

2024-01-25 10:52 UTC, atodorov commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        const alith = new ethers.Wallet('0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133').connect(
Note to self: `lender` and `borrower` don't make sense anymore, I will push a PR to update these to something like `alice` & `bob`.

2024-01-25 10:52 UTC, atodorov commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +            .call(contract, randomEvmAccount().address, parseEther('10'));
Question:  Does this call reduce the balance of `alith` ? 

Assuming that's the case we would like to use well known address for the receiver, instead of a random account. 

The reason being is that we use the same test suite against multiple targets (local, Devnet, Testner & Mainnet) and for Testnet & Mainnet we may want to recirculate the funds used during testing. 

See above for the usage of `createSigner` and `substrateAddressToEvmAddress`. 

See https://github.com/gluwa/creditcoin/blob/dev/integration-tests/src/mainnetSetup.ts#L4 for an example how the `createSigner` function looks for CC2 Mainnet.

2024-01-25 10:52 UTC, atodorov commented on .github/workflows/ci.yml
> +          args: --release --features fast-runtime --features=evm-tracing
Can you please also rename the CI job name to `build-creditcoin-node-for-ci` to reflect the new reality.

2024-01-25 10:52 UTC, atodorov commented on .github/workflows/ci.yml
> +            --ethapi=debug,trace,txpool \
Adding this comment here for visibility. 

From the [original code review](https://github.com/gluwa/creditcoin3/pull/169#discussion_r1452283533):

We should add all of the newly committed Cargo.toml files into dependabot.yml in case there's ever a dependency which doesn't come from the workspace. I will send a PR to check for anything that is missing!

2024-01-25 11:43 UTC, atodorov commented on .github/workflows/ci.yml
> +            --ethapi=debug,trace,txpool \
Additional CI checks for these missing Cargo.toml files are in https://github.com/gluwa/creditcoin3/pull/187, the list of missing files can be found at https://github.com/gluwa/creditcoin3/actions/runs/7653952405/job/20856903770?pr=187.

2024-01-25 13:18 UTC, frankli-dev commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        const alith = new ethers.Wallet('0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133').connect(
The value is private key of alice account. Not an address. Any good idea to get that?

2024-01-25 13:48 UTC, frankli-dev commented on .github/workflows/ci.yml
> +            --ethapi=debug,trace,txpool \
Cool. Thanks @atodorov

2024-01-25 13:49 UTC, frankli-dev commented on .github/workflows/ci.yml
> +          args: --release --features fast-runtime --features=evm-tracing
done

2024-01-25 13:51 UTC, frankli-dev commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        provider = new WebSocketProvider(ALICE_NODE_URL);
done

2024-01-25 14:31 UTC, atodorov commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        const alith = new ethers.Wallet('0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133').connect(
> The value is private key of alice account. Not an address.

arght. Thanks for explanation. 

> Any good idea to get that?

You can define another function inside `blockchainSetup.ts` similar to `createSigner` to return private keys. We can then override this function in other config files as necessary. In general for a non-local environment we pass these private keys via ENV variables before starting the test suite. The details around this are in https://github.com/gluwa/creditcoin/blob/dev/integration-tests/README.md

2024-01-29 15:27 UTC, atodorov commented on cli/src/test/blockchain-tests/evm-tracing.test.ts
> +        const alith = new ethers.Wallet('0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133').connect(
@frankli-dev see `(global as any).CREDITCOIN_EVM_PRIVATE_KEY ` from https://github.com/gluwa/creditcoin3/pull/191/commits/613ac2c1844f4a02980a62a9a9124e30dd9c39e7, #191

2024-01-30 15:10 UTC, atodorov requested changes
- needs addressing https://github.com/gluwa/creditcoin3/pull/182#discussion_r1466189918
- ideally also a rebase

2024-01-30 17:48 UTC, frankli-dev commented
> * needs addressing [CSUB-1011: Tracing rpc tests #182 (comment)](https://github.com/gluwa/creditcoin3/pull/182#discussion_r1466189918)
> * ideally also a rebase

Done

2024-01-30 18:39 UTC, atodorov approved these changes

2024-01-30 18:39 UTC, merged