CUSB-1034: Additional integration tests for CLI EVM cmd
gluwa/creditcoin3 pull request #225
Opened 2024-02-07 18:41 UTC by zacharyfrederick

2024-02-12 15:44 UTC, atodorov requested changes
A few more improvements can be made here

2024-02-12 15:44 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +        expect(CLI(`evm fund --evm-address ${evmAccount.address} --amount 1000000`)).toThrow(Error);
Can actually assert on the actual error, see for example:
https://github.com/gluwa/creditcoin3/pull/231/files#diff-74700920f7157491acd41e55326e6c9b1e31d905f11ee26db196053c171e9466R99

2024-02-12 15:44 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +        const { api } = await newApi(ALICE_NODE_URL);
this is `beforeAll`

2024-02-12 15:44 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +        const CLI = CLIBuilder({ CC_SECRET: caller.secret });
This is common setup so best single it out in `beforeEach`, see for example https://github.com/gluwa/creditcoin3/pull/231/files#diff-74700920f7157491acd41e55326e6c9b1e31d905f11ee26db196053c171e9466R25

2024-02-12 17:09 UTC, zacharyfrederick commented on cli/src/test/integration-tests/evm.test.ts
>  describe('EVM commands', () => {
Is this what you are doing in the other PR? Should I just consider this resolved in regards to this ticket?

2024-02-12 17:16 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
>  describe('EVM commands', () => {
It is similar changes, but a different source file.

2024-02-12 17:19 UTC, atodorov requested changes
Minor change requested. The rest LGTM (more reorganization to follow up in a separate PR).

2024-02-12 17:19 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +    }, 100_000);
missing an `afterAll` to disconnect the api object.

I think it will generate `This usually means that there are asynchronous operations that weren't stopped in your tests` error at the end.

2024-02-13 09:12 UTC, atodorov requested changes
One small item left todo, the rest looks good.

2024-02-13 09:12 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +            await api.disconnect();
this is repeated multiple times. Should go into an `afterAll` block.

2024-02-13 17:05 UTC, atodorov submitted a review, later dismissed

2024-02-13 17:08 UTC, atodorov commented on cli/src/test/integration-tests/evm.test.ts
> +            const CLI2 = CLIBuilder({ env: { EVM_SECRET: evmAccount1.mnemonic } });
hmmm 2 things here: 

1). Do we need `env:` key here. Other invocations of CLIBuilder don't pass secrets like that
2) probably needs quotes b/c mnemonic contains white space.

2024-02-13 17:30 UTC, zacharyfrederick commented on cli/src/test/integration-tests/evm.test.ts
> +            const CLI2 = CLIBuilder({ env: { EVM_SECRET: evmAccount1.mnemonic } });
Addressed 1). I think 2) is okay will update based on tests

2024-02-13 17:44 UTC, zacharyfrederick commented on cli/src/test/integration-tests/evm.test.ts
> +            const CLI2 = CLIBuilder({ env: { EVM_SECRET: evmAccount1.mnemonic } });
Changes to the existential balance amount broke some tests. Updating and rebasing

2024-02-14 15:17 UTC, pLabarta approved these changes

2024-02-14 15:59 UTC, merged