[CSUB-1046] Set MaxAuthorities to 1000
gluwa/creditcoin3 pull request #242
Opened 2024-02-20 17:40 UTC by pLabarta

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-02-20 17:47 UTC, atodorov approved these changes

2024-02-21 10:01 UTC, atodorov requested changes
See Rustfmt failure! Needs update. 

The rest of the failures are tracked in CSUB-1054. Preferably we should block on it before merging more untested things.

2024-02-23 11:27 UTC, atodorov approved these changes

2024-02-27 17:04 UTC, zacharyfrederick submitted a review, later dismissed

2024-03-01 10:05 UTC, atodorov commented
FTR rebased on top of `dev` and had to update the version to 3.21.0

2024-03-01 11:17 UTC, atodorov approved these changes

2024-03-01 11:23 UTC, beqaabu approved these changes

2024-03-01 13:31 UTC, merged