Integration Tests fix
gluwa/creditcoin3 pull request #243
Opened 2024-02-21 18:20 UTC by frankli-dev

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-02-22 10:00 UTC, atodorov commented on .github/workflows/wasm.yml
>          run: |
Test for devnet chainspec failing, see:
https://github.com/gluwa/creditcoin3/actions/runs/7994072110/job/21831530070

2024-02-26 09:58 UTC, atodorov commented on .github/workflows/wasm.yml
> +          BUILD_OPTIONS: "--features devnet"
FTR this is in https://github.com/gluwa/creditcoin3/pull/248

2024-02-26 13:34 UTC, atodorov requested changes

2024-02-26 13:34 UTC, atodorov commented on runtime/src/lib.rs
> +const BLOCKS_FOR_FASTER_EPOCH: u32 = if cfg!(feature = "devnet") {
@frankli-dev this new compiler flag isn't working at all:

```
cargo build --release --features devnet
error: none of the selected packages contains these features: devnet
```

2024-02-26 14:00 UTC, atodorov requested changes

2024-02-27 08:55 UTC, atodorov requested changes

2024-02-27 08:55 UTC, atodorov commented on .github/workflows/wasm.yml
> +        env:
@frankli-dev the ENV var name is incorrect here, see
https://github.com/chevdor/srtool-actions?tab=readme-ov-file#environmental-variables-and-build_opts

2024-02-27 10:30 UTC, atodorov commented on .github/workflows/wasm.yml
>          run: |
I have a fix for this in https://github.com/gluwa/creditcoin3/pull/249 (will need some more adjustments after this and #248 are merged)

2024-02-27 16:11 UTC, zacharyfrederick commented on runtime/src/lib.rs
> +};
The naive fix is 
```rust 
macro_rules! prod_or_fast {
    ($prod: expr, $fast: expr) => {
        if cfg!(feature = "fast-runtime") || cfg!(feature = "devnet") {
            $fast
        } else {
            $prod
        }
    };
}
```

2024-02-27 16:16 UTC, zacharyfrederick commented on runtime/src/lib.rs
> +const BLOCKS_FOR_FASTER_EPOCH: u32 = if cfg!(feature = "devnet") {
You need to add `devnet=[]` to the `cargo.toml` of the runtime.

You can add it right after `fast-runtime`.

```
[features]
default = ["std"]
evm-tracing = ["creditcoin3-evm-tracer"]
fast-runtime = []
devnet = []
```

2024-02-27 16:25 UTC, atodorov commented on runtime/src/lib.rs
> +};
I think this is not the best fix b/c it is hiding the logic inside of the macro instead of the logic being visible where used (e.g. in lib.rs). 

Also it is equally easy that we specify 2 feature flags where needed instead of only 1.

2024-02-27 16:49 UTC, zacharyfrederick commented on runtime/src/lib.rs
> +};
Okay, revert the macro. Use the second devnet flag like this? 

```rust
pub const EPOCH_DURATION_IN_BLOCKS: u32 = (prod_or_fast!(12 * HOURS, BLOCKS_FOR_FASTER_EPOCH) && !cfg!(feature="devnet")) || BLOCKS_FOR_FASTER_EPOCH;

```

2024-02-27 16:55 UTC, atodorov commented on runtime/src/lib.rs
> +};
IMO the discussion of "which implementation approach to take in order for the code to be elegant and everyone on the team to like it" should happen *after* the immediate patches for CSUB-1054 are merged. 

For now I am happy with the approach of specifying the 2 features together b/c that's how the code was intended to be used originally and b/c further changes have been implemented already, which assume the same approach. 

LMK if you want me to open a Jira ticket for refactoring and we can hash-out the details there ?

2024-02-27 16:59 UTC, zacharyfrederick commented on runtime/src/lib.rs
> +};
Also, I'm not even sure we need a macro? It seems like pretty simple logic

2024-02-28 12:43 UTC, atodorov commented on .github/workflows/wasm.yml
> +        env:
Fixed in -> https://github.com/gluwa/creditcoin3/pull/253

2024-02-28 12:44 UTC, atodorov commented on runtime/src/lib.rs
> +const BLOCKS_FOR_FASTER_EPOCH: u32 = if cfg!(feature = "devnet") {
Builds flags fixed in -> https://github.com/gluwa/creditcoin3/pull/253. Working on the additional CI job!

2024-02-28 14:31 UTC, atodorov commented on runtime/src/lib.rs
> +const BLOCKS_FOR_FASTER_EPOCH: u32 = if cfg!(feature = "devnet") {
Additional patches for the CI build jobs -> https://github.com/gluwa/creditcoin3/pull/253/commits/a04d2a256447538a7acadc9ee091c2511492372f (also #253). 

LGTM, need to wait for all of the CI jobs to finish before we can merge #253.

2024-02-28 18:08 UTC, atodorov commented
Merged in https://github.com/gluwa/creditcoin3/pull/253

2024-02-28 18:08 UTC, closed without merging