[CSUB-1060] Rename creditcoin3 CLI to just creditcoin
gluwa/creditcoin3 pull request #247
Opened 2024-02-22 21:09 UTC by pLabarta

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-02-23 11:30 UTC, atodorov requested changes
There are some legit failures that need fixing: (preferably we block on CSUB-1054 as well):
MegaLinter, docker-build, sanity-test-cli

2024-03-06 15:47 UTC, atodorov requested changes
CI jobs still failing with genuine issues:

- docker-build
- sanity-test-cli

2024-03-07 12:32 UTC, atodorov commented
@pLabarta note: I've rebased; squashed your commits and added changes to satisfy the rest of the failing CI jobs.

2024-03-07 13:53 UTC, atodorov approved these changes

2024-03-07 15:07 UTC, frankli-dev approved these changes

2024-03-08 02:02 UTC, merged