DRAFT: Devnet release upgrade
gluwa/creditcoin3 pull request #248
Opened 2024-02-23 16:03 UTC by zacharyfrederick

2024-02-23 16:36 UTC, zacharyfrederick commented on .github/workflows/release.yml
> +        if: ${{ env.TAG_NAME }} == 'devnet'
I think you can use `contains`. [Docs here ](https://docs.github.com/en/actions/learn-github-actions/expressions#contains)

So 
```
if: contains(${{ env.TAG_NAME }}, 'devnet') == true
```

2024-02-23 16:58 UTC, zacharyfrederick commented
@atodorov This should be a lot closer. Lmk what ya think

2024-02-23 17:12 UTC, atodorov requested changes

2024-02-23 17:12 UTC, atodorov commented on .github/workflows/release.yml
> +          docker build -t gluwa/creditcoin3:${{ env.TAG_NAME }} -f Dockerfile_Devnet .
`Dockerfile_Devnet` doesn't exist and IMO it isn't needed. You can pass the build options to docker and use them as if using an environment variable. See for example:
https://github.com/gluwa/creditcoin3-staking-dashboard/blob/dev/.github/workflows/docker.yml#L43

2024-02-23 17:12 UTC, atodorov commented on .github/workflows/release.yml
> +
extra new line

2024-02-23 17:12 UTC, atodorov commented on .github/workflows/release.yml
> +          BUILD_OPTIONS: --release ${{ needs.setup.outputs.build_options }}
1). This job does not specify `setup` in its dependency specification. 

2) The name of the environment variable is incorrect -> https://github.com/chevdor/srtool-actions?tab=readme-ov-file#environmental-variables-and-build_opts

2024-02-23 17:12 UTC, atodorov commented on .github/workflows/release.yml
> +          args: --release ${{ needs.setup.outputs.build_options}}
This job does not specify setup in its dependency specification.

2024-02-23 17:12 UTC, atodorov commented on .github/workflows/release.yml
> +      build_options: ${{ contains( env.TAG_NAME, 'devnet') && '--features devnet' || '' }}
I am not certain that this is going to work b/c environment variables are not propagated automatically between jobs as far as I know.  `TAG_NAME` is coming from `sanity-check` and we also define it independently inside every job that uses it. 

A better approach will be:

1) Make `TAG_NAME` an output of sanity-check, update all other jobs respectively b/c they depend on sanity-check anyway & remove the redundant steps redefining the ENV variable from the rest of the jobs.

2) Place `setup` after `sanity-check` and make it depend on it. That way you can consume 
`sanity-check.outputs.tag_name` inside `setup`.

2024-02-26 09:58 UTC, atodorov requested changes
See MegaLinter failures too https://github.com/gluwa/creditcoin3/actions/runs/8022463304/job/21916863418?pr=248

2024-02-26 17:16 UTC, atodorov requested changes

2024-02-26 17:16 UTC, atodorov commented on .github/workflows/release.yml
> +  setup:
The current definition is invalid, yields:
```
No steps defined in `steps` and no workflow called in `uses` for the following jobs: setup
```

See https://github.com/gluwa/creditcoin3/actions/runs/8052408066

It needs a dummy step which doesn't do anything useful.

2024-02-26 17:16 UTC, atodorov commented on .github/workflows/release.yml
> +      TAG_NAME_OUTPUT: ${{ steps.step2.output.TAG_NAME }}
Typo in `outputs`

```suggestion
      TAG_NAME: ${{ steps.step2.outputs.TAG_NAME }}
```

2024-02-26 17:29 UTC, zacharyfrederick commented on .github/workflows/release.yml
> +      docker_build_options: ${{ contains(needs.sanity-check.outputs.TAG_NAME_OUTPUT, 'devnet') && 'BUILD_ARGS="--features devnet"'  || '' }}
The dockerfile uses env variable `BUILD_ARGS` as the feature flag.  So I need to have that value dropped down to the the docker level and preserve the string. What is the smarter way to do it?

2024-02-26 17:34 UTC, atodorov requested changes

2024-02-26 17:34 UTC, atodorov commented on .github/workflows/release.yml
> +          echo "Build options: ${{ contains( needs.sanity-check.outputs.TAG_NAME, 'devnet') && '--features devnet, fast-runtime' || '' }}"
This `echo` isn't stable b/c it duplicates the expression above. The best way for this would be

1) add a step to set the otput vars
2) inside the DEBUG step echo the output vars from the previous step
3) inside the outputs section use the steps from the step defining the vars

2024-02-26 17:34 UTC, atodorov commented on Dockerfile
> +    cargo build --release $BUILD_ARGS
MegaLinter wants quotes here.

2024-02-26 17:34 UTC, atodorov commented on Dockerfile
> +    cargo build --release $BUILD_ARGS
Ideally also you add at the top of this file:

`ARG BUILD_ARGS=""` in case this isn't defined

2024-02-26 17:36 UTC, atodorov commented on .github/workflows/release.yml
> +      docker_build_options: ${{ contains(needs.sanity-check.outputs.TAG_NAME_OUTPUT, 'devnet') && 'BUILD_ARGS="--features devnet"'  || '' }}
```
docker build -t gluwa/creditcoin3:${{needs.sanity-check.outputs.TAG_NAME  }} --build-arg BUILD_ARGS=${{ needs.setup.outputs.build_options }}".
```

2024-02-26 18:23 UTC, atodorov requested changes

2024-02-26 18:23 UTC, atodorov commented on .github/workflows/release.yml
> +          echo "build_options = ${{ steps.set-build-options.outputs.build_options}}""
Redundant double-quote at the end will cause bash & MegaLinter failures.

2024-02-26 18:48 UTC, atodorov requested changes

2024-02-26 18:48 UTC, atodorov commented on Dockerfile
> +    cargo build --release "$BUILD_ARGS"
hmmm, this causes build failures because of the quotes I think. 

You can try `${BUILD_ARGS}` syntax instead. If MegaLinter is still not happy we should disable the warnings it gives.

2024-02-27 08:52 UTC, atodorov commented on Dockerfile
> +    cargo build --release "$BUILD_ARGS"
FTR the `${BUILD_ARGS}` syntax works however MegaLinter still isn't happy so just update the list of ignored issues in Dockerfile.

2024-02-27 10:28 UTC, atodorov requested changes
Changes requested b/c builds are failing:

PR used for debugging -> https://github.com/gluwa/creditcoin3/pull/251

Tag used for debugging -> https://github.com/gluwa/creditcoin3/releases/tag/xx.yy.zz-devnet

release.yml execution from the above tag -> https://github.com/gluwa/creditcoin3/actions/runs/8063126555

2024-02-27 10:28 UTC, atodorov commented on .github/workflows/release.yml
> +          echo "build_options=${{ contains( needs.sanity-check.outputs.TAG_NAME, 'devnet') && '--features devnet, fast-runtime' || '' }}" >> "$GITHUB_OUTPUT"
The way `--features` is specified is not valid cargo syntax:

```
cargo build --release --features devnet, fast-runtime
error: unexpected argument 'fast-runtime' found

Usage: cargo build [OPTIONS]

For more information, try '--help'.
```

See https://github.com/gluwa/creditcoin3/actions/runs/8063126555/job/22024333191 from https://github.com/gluwa/creditcoin3/releases/tag/xx.yy.zz-devnet

It is either `--features "devnet fast-runtime"` with the quotes or specified twice like so:
`--features devnet --features fast-runtime`

2024-02-27 10:28 UTC, atodorov commented on .github/workflows/release.yml
> +          docker build -t gluwa/creditcoin3:${{needs.sanity-check.outputs.TAG_NAME  }} --build-arg="BUILD_ARGS=${{ needs.setup.outputs.build_options }}".
Results in:

```
Run docker build -t gluwa/creditcoin3:xx.yy.zz-devnet --build-arg="BUILD_ARGS=--features devnet, fast-runtime".
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
```

see https://github.com/gluwa/creditcoin3/actions/runs/8063126555/job/22024334310


Try:

```suggestion
docker build -t gluwa/creditcoin3:${{needs.sanity-check.outputs.TAG_NAME  }} --build-arg BUILD_ARGS="${{ needs.setup.outputs.build_options }}" .
```

2024-02-27 14:53 UTC, zacharyfrederick commented on .github/workflows/release.yml
> +          docker build -t gluwa/creditcoin3:${{needs.sanity-check.outputs.TAG_NAME  }} --build-arg="BUILD_ARGS=${{ needs.setup.outputs.build_options }}".
that is the most embarrassing one of all

2024-02-27 15:20 UTC, zacharyfrederick commented
@atodorov Added the same build option setup logic to the wasm.yml CI file

2024-02-27 15:36 UTC, atodorov requested changes
Let's drop the last changes to `wasm.yml` because they are opening a bigger can of worms!

2024-02-27 15:36 UTC, atodorov commented on .github/workflows/wasm.yml
> +  sanity-check:
All of this is actually not necessary and will probably even going to cause problems.

This CI job is used as part of regular PRs, not on tag pushes and will fail because you don't have tags on pull requests.

2024-02-27 15:36 UTC, atodorov commented on .github/workflows/wasm.yml
> +          echo "${{ env.TAG_NAME }}" | grep -E "mainnet|testnet|devnet"
This will fail on merges to any of the target branches b/c the tag name will be incorrect anyway.

2024-02-27 15:36 UTC, atodorov commented on .github/workflows/wasm.yml
> +          echo "build_options = ${{ steps.set-build-options.outputs.build_options}}"
this isn't really needed b/c this CI job isn't part of the release process.

2024-02-27 15:36 UTC, atodorov commented on .github/workflows/wasm.yml
> +          echo "build_options=${{ contains( needs.sanity-check.outputs.TAG_NAME, 'devnet') && '--features devnet --features fast-runtime' || '' }}" >> "$GITHUB_OUTPUT"
If you want to be thorught and provide build_options only when running on `dev` or a PR against `dev` this aproach won't work b/c there are no tags here. 

Instead the approach should be similar to https://github.com/gluwa/creditcoin3/blob/dev/.github/workflows/runtime-upgrade.yml#L38 where values are configured depending on the target branch of a PR.  (github.base_ref)

WARNING: when running from a branch after a merge, not a PR then you don't have github.base_ref but instead      github.ref and the value is slightly different (see line 92 in this file).

2024-02-27 15:36 UTC, atodorov commented on .github/workflows/wasm.yml
> +          BUILD_OPTS: "--release ${{ needs.setup.outputs.BUILD_ARGS }}"
This is going to be fine for now b/c the only situation when this wasm output is consumed is in `upgrade-devnet` which is executed only when running on the `dev` branch (line 92).

2024-02-27 15:48 UTC, atodorov commented on .github/workflows/release.yml
> +          BUILD_OPTS: --release ${{ needs.setup.outputs.build_options }}
Currently failing b/c of https://github.com/gluwa/creditcoin3/pull/243#discussion_r1502624717. We need #243 resolved/merged first before making progress here!

2024-02-27 16:08 UTC, atodorov commented on .github/workflows/wasm.yml
> +          BUILD_OPTS: "--features devnet"
**NOTE:** the comment above applies to the WASM build step in `release.yml`, not to `wasm.yml`

2024-02-27 16:16 UTC, atodorov commented on .github/workflows/wasm.yml
> +          BUILD_OPTS: "--features devnet"
https://github.com/gluwa/creditcoin3/commit/705910e62c9d39a07e0bd2245931dc3fe37d3a52

2024-02-27 16:17 UTC, atodorov requested changes

2024-02-27 16:17 UTC, atodorov commented on .github/workflows/release.yml
> +          BUILD_OPTS: --release "${{ needs.setup.outputs.build_options }}"
Needs this patch: 

```suggestion
          BUILD_OPTS: "--release ${{ needs.setup.outputs.build_options }}"
```

https://github.com/gluwa/creditcoin3/commit/705910e62c9d39a07e0bd2245931dc3fe37d3a52

2024-02-27 16:49 UTC, atodorov commented on Dockerfile
> +    cargo build --release ${BUILD_ARGS}
@zacharyfrederick  the declaration of `BUILD_ARGS` needs to move into the appropriate build stage.

See:
- https://github.com/gluwa/creditcoin3/commit/640fdfd4ed735892b9db5426867cf4a68269524f
- https://github.com/gluwa/creditcoin3/actions/runs/8068323904/job/22040815572
- and logs
```
> [rust-builder 4/4] RUN source ~/.cargo/env &&     cargo build --release --features devnet --features fast-runtime:
```

2024-02-28 19:13 UTC, atodorov commented
This is ready for review (the Ready for review button currently results in an error)

- Build jobs from the `xx.yy.10-devnet` tag -> https://github.com/gluwa/creditcoin3/actions/runs/8085322225 all show the build options `--release --feature fast-runtime --feature devnet`
- [CI / integration-test-chainspec-devnet](https://github.com/gluwa/creditcoin3/actions/runs/8085237160/job/22093252857?pr=248) is a known failure, fixed in #249 
-

2024-02-28 19:13 UTC, atodorov approved these changes

2024-02-29 09:26 UTC, merged