chore: update author in Cargo.toml
gluwa/creditcoin3 pull request #272
Opened 2024-03-19 10:58 UTC by DylanVerstraete

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-03-19 11:43 UTC, atodorov commented on Cargo.toml
> +authors = ["Gluwa Inc. <info@gluwa.com>"]
I'm not sure who reads this address. Ideally we'd like to be using an address that reaches the team directly but I'm not aware of such an address.

The rest LGTM.

2024-03-19 19:02 UTC, beqaabu commented on .github/CODEOWNERS
> +* @gluwa/blockchain-engineering
I think @gluwa/creditcoin would make more sense, we are all members there, but not sure

2024-03-20 08:56 UTC, DylanVerstraete commented on .github/CODEOWNERS
> +* @gluwa/blockchain-engineering
Alright!

2024-03-20 09:40 UTC, beqaabu approved these changes

2024-03-20 10:02 UTC, atodorov approved these changes
LGTM

2024-03-20 10:03 UTC, atodorov requested changes
GitHub isn't letting me merge this. It probably wants a rebase :-(.

2024-03-20 10:10 UTC, atodorov approved these changes

2024-03-20 10:11 UTC, merged