chore: add bootnodes to chainspecs
gluwa/creditcoin3 pull request #276
Opened 2024-03-19 14:50 UTC by DylanVerstraete

# Description of proposed changes

Harcoded the bootnodes in the chainspecs (dev and test). You can now easily spin up a node in either of the 2 networks like:

```
./target/release/creditcoin3-node -d /var/tmp/devnet --chain chainspecs/devnetSpecRaw.json
```

This makes it easy for developers to quickly sync nodes with binaries built from source.

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-03-19 15:28 UTC, atodorov requested changes
Can you squash both commits together ? No need to have bootnodes added and then removed in the history IMO.

2024-03-19 15:28 UTC, atodorov commented on chainspecs/devnetSpecRaw.json
> +  "bootNodes": [],
Do you mind adding a check which makes sure that there are no boot nodes defined in any of the chain-specs ?

Option 1 - add it somewhere here: 
https://github.com/gluwa/creditcoin3/blob/dev/.github/workflows/ci.yml#L91

can be a simple grep/bash script or maybe slightly better parsing the json with `jq`.

Option 2  - we have a dedicated section for chainspec checks which executes one of the existing integration tests with a different config file: 
https://github.com/gluwa/creditcoin3/blob/dev/.github/workflows/ci.yml#L687


Either one will work but 1) should fail faster so is probably better.

2024-03-19 15:45 UTC, DylanVerstraete commented on chainspecs/devnetSpecRaw.json
> +  "bootNodes": [],
Implemented 1

2024-03-19 19:07 UTC, beqaabu submitted a review, later dismissed
Nice

2024-03-20 09:59 UTC, atodorov requested changes
LGTM but the last commit isn't expected. I think this PR needs a rebase and the commit [Auto-update TypeScript type definitions](https://github.com/gluwa/creditcoin3/pull/276/commits/2b36411b249c3fddddba9b345da9ad09a4d70bb3) should be removed.

2024-03-20 17:10 UTC, atodorov approved these changes
LGTM, waiting for CI jobs to report green before merging.

2024-03-21 11:25 UTC, beqaabu approved these changes

2024-03-21 18:53 UTC, merged