feat(cli): check min bond amount before calling the actual extrinsic
gluwa/creditcoin3 pull request #283
Opened 2024-03-21 13:50 UTC by DylanVerstraete

# Description of proposed changes

See: https://gluwa.atlassian.net/browse/CSUB-1075

Cli will now check for the min validator bond amount before submitting the bond extrinsic, if the amount is not enough it will return an error to the client

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-03-21 14:14 UTC, DylanVerstraete commented
@atodorov not sure why on testnet the minNominatorBond and minValidatorBond are different, can you please explain me why? Should I also take this into account here?

2024-03-21 14:56 UTC, atodorov requested changes
Some changes required.

2024-03-21 14:56 UTC, atodorov commented on cli/src/test/integration-tests/bond.test.ts
> +                expect(error.exitCode).toEqual(1);
missing assert on the actual error message, see other test scenarios for example.

2024-03-21 14:56 UTC, atodorov commented on cli/src/test/integration-tests/bond.test.ts
> +            const oldBalance = await getBalance(caller.address, api);
`oldBalance` -> `balance`

2024-03-21 14:56 UTC, atodorov commented on cli/src/lib/staking/bond.ts
> +        if (BigInt(amount.toString()) < min_bond_amount.toNumber() * 1e18) {
`1e18` -> `MICROUNITS_PER_CTC`, no ?

2024-03-21 14:56 UTC, atodorov commented on cli/src/lib/staking/bond.ts
> +        if (BigInt(amount.toString()) < min_bond_amount.toNumber() * 1e18) {
On a side note I see that both `lib/constants.ts` and `lib/balance/index.ts` export the MICROUNITS_PER_CTC constant. We need only one of them. I think `lib/constants.ts` is used more widely.

2024-03-21 14:58 UTC, atodorov commented
> @atodorov not sure why on testnet the minNominatorBond and minValidatorBond are different

If you mean "different from one another" then the answer is because they are different settings and their values have been decided by stakeholders.

If you mean something else please clarify . 

> Should I also take this into account here?

`minNominatorBond` is related to nominating validators, not becoming a validator. The cli commands don't expose the option for nominating (that is the Staking Dashboard) so this can be ignored IMO.

2024-03-21 15:36 UTC, DylanVerstraete commented on cli/src/lib/staking/bond.ts
> +        if (BigInt(amount.toString()) < min_bond_amount.toNumber() * 1e18) {
:+1:

2024-03-22 09:42 UTC, atodorov requested changes
Minor change requested.

2024-03-22 09:42 UTC, atodorov commented on cli/src/test/integration-tests/bond.test.ts
> +            await setMinBondConfig(api, 0);
Note: if this test scenario fails for whatever reason before reaching this line the minimum bond config will stay in place and possible break other sceanrios which would be executed afterwards. 

Ideally this call should happen in `afterEach()` to reduce fragility of the test suite.

2024-03-22 10:32 UTC, atodorov reviewed
Q: will there be follow-up PRs for `wizard` and `validate` commands ?

2024-03-22 10:54 UTC, DylanVerstraete commented
> Q: will there be follow-up PRs for `wizard` and `validate` commands ?

For tests? 

Because the functionality implemented will work for those 2 commands since they call the bond function

2024-03-22 11:23 UTC, DylanVerstraete commented
> Q: will there be follow-up PRs for wizard and validate commands ?

You mean `bond` and `wizard` commands? `validate` doesn't do bonding

2024-03-22 12:52 UTC, atodorov requested changes
minor changes requested however I am seeing a traceback locally,.

2024-03-22 12:52 UTC, atodorov commented on cli/src/lib/staking/bond.ts
> +            throw new Error('Amount to bond must be at least the minimum validator bond amount');
Error message can be improved by showing the exact value.

2024-03-22 12:52 UTC, atodorov commented on cli/src/lib/staking/bond.ts
> +        const min_bond_amount = await api.query.staking.minValidatorBond();
nit pick: min_bond_amount -> minBondAmount, or better yet minValidatorBond.

2024-03-22 12:52 UTC, atodorov commented on cli/src/test/integration-tests/bond.test.ts
> +                CLI('bond --amount 50');
```
$ node dist/cli.js bond -u ws://127.0.0.1:9955 --amount 50 -r Stash 
✔ Specify a seed phrase for the caller account … ****************************************************************************
Creating bond transaction...
Reward destination: Stash
Amount: 50.000000000000000000 CTC
✔ Continue? … yes
Amount: 50000000000000000000
/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
                    ^

Error: Number can only safely store up to 53 bits
    at assert (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/bn.js/lib/bn.js:6:21)
    at u128.toNumber (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/bn.js/lib/bn.js:547:7)
    at bond (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/lib/staking/bond.js:20:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.bondAction (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/commands/staking/bond.js:37:26)

Node.js v20.11.1
```


Not sure why the second assertion doesn't fail in CI but that's preventing me from exercising these changes locally.

2024-03-22 12:52 UTC, atodorov commented on cli/src/test/integration-tests/bond.test.ts
> +                CLI('bond --amount 50');
FTR I have configured:

![image](https://github.com/gluwa/creditcoin3/assets/1002300/308cb961-c822-4ee2-abea-c7c2c716354f)

which is the same as Testnet.

2024-03-22 13:14 UTC, DylanVerstraete commented on cli/src/lib/staking/bond.ts
> +        const min_bond_amount = await api.query.staking.minValidatorBond();
I'm not used to writing js anymore :D

2024-03-22 13:15 UTC, DylanVerstraete commented on cli/src/test/integration-tests/bond.test.ts
> +                CLI('bond --amount 50');
Hmm, I will check

2024-03-22 14:16 UTC, atodorov commented
> > Q: will there be follow-up PRs for `wizard` and `validate` commands ?
> 
> For tests?
> 

Both for tests and for the `validate` command itself. 

> Because the functionality implemented will work for those 2 commands since they call the bond function



`wizard` command will need tests: 

```
$ node dist/cli.js wizard -u ws://127.0.0.1:9955 -r Stash --amount 1000
🧙 Running staking wizard...
✔ Specify a seed phrase for the caller account … ****************************************************************************
Using the following parameters:
💰 Stash account: 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
🪙 Amount to bond: 1000.000000000000000000 CTC
🎁 Reward destination: Stash
📡 Node URL: ws://127.0.0.1:9955
💸 Commission: 0
🔐 Blocked: No
✔ Continue? … yes
Sending bond transaction...
Amount: 1000000000000000000000
/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/lib/staking/bond.js:23
            throw new Error(`Amount to bond must be at least: ${amountMsg.toString()} CTC (min validator bond amount)`);
                  ^

Error: Amount to bond must be at least: 20000 CTC (min validator bond amount)
    at bond (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/lib/staking/bond.js:23:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bondRoutine (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/commands/staking/wizard.js:164:30)
    at async Command.<anonymous> (/home/gluwa/creditcoin-3.0/creditcoin3/cli/dist/commands/staking/wizard.js:78:13)

Node.js v20.11.1
[gluwa@fedora cli]$ echo $?
1
```


`validate` (staking.validate) checks MinValidatorBond explicitly and we need to check this on the cli side b/c it's easy to end up in a situation where validate will fail when trying to send the extrinsic. For example:

```
$ node dist/cli.js bond -u ws://127.0.0.1:9955 --amount 21000
✔ Specify a seed phrase for the caller account … ****************************************************************************
Creating bond transaction...
Reward destination: Staked
Amount: 21000.000000000000000000 CTC
✔ Continue? … yes
Amount: 21000000000000000000000
Sending transaction...
Transaction included at blockHash 0xfa485f06d0e3718299841a9e78ae881c016fb366e84e1230e3e55cba668f1785


$ node dist/cli.js unbond -u ws://127.0.0.1:9955 --amount 2000
✔ Specify a seed phrase for the caller account … ****************************************************************************
Sending transaction...
Transaction included at blockHash 0x31a8bcd35e9c11181196336f9ae573fcf4f8db89a65fc54a00be19c3a9b0597d


$ node dist/cli.js status -u ws://127.0.0.1:9955 --substrate-address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
Validator 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp:
┌────────────────┬───────────────────────────────────────────────────────┐
│ Status         │                                                       │
├────────────────┼───────────────────────────────────────────────────────┤
│ Bonded         │ Yes                                                   │
├────────────────┼───────────────────────────────────────────────────────┤
│ Validating     │ No                                                    │
├────────────────┼───────────────────────────────────────────────────────┤
│ Waiting        │ No                                                    │
├────────────────┼───────────────────────────────────────────────────────┤
│ Active         │ No                                                    │
├────────────────┼───────────────────────────────────────────────────────┤
│ Can withdraw   │ No                                                    │
├────────────────┼───────────────────────────────────────────────────────┤
│ Next unlocking │ 2000.000000000000000000 CTC in 17 minutes, 25 seconds │
└────────────────┴───────────────────────────────────────────────────────┘

$ node dist/cli.js set-keys -r -u ws://127.0.0.1:9955 
✔ Specify a seed phrase for the caller account … ****************************************************************************
Sending transaction...
Transaction included at blockHash 0xac5613056e974016814302793e727ce30f55d5f095fc3315436308458ccdcb26


$ node dist/cli.js validate -u ws://127.0.0.1:9955 --commission 5 
✔ Specify a seed phrase for the caller account … ****************************************************************************
Creating validate transaction...
Creating validate transaction with params:
Comission: 50000000
Blocked for new nominators: false
Sending transaction...
Transaction failed with error: "staking.InsufficientBond: Cannot have a validator or nominator role, with value less than the minimum defined by governance (see `MinValidatorBond` and `MinNominatorBond`). If unbonding is the intention, `chill` first to remove one's role as validator/nominator." at block 0xa05f1199858ce04a6137a38145c77c9d9c239aabb8e76944154006770e9b1503
```

2024-03-25 11:34 UTC, atodorov requested changes
Soe changes requested, performing manual tests b/c one of the automated scenarios didn't fail as expected.

2024-03-25 11:34 UTC, atodorov commented on cli/src/test/integration-tests/wizard.test.ts
> +            } catch (error: any) {
this doesn't look right. It is using a bond amount > 500 which isn't supposed to fail, yet the test reports all good. That is not what I expected.

2024-03-25 11:34 UTC, atodorov commented on cli/src/test/integration-tests/wizard.test.ts
> +            await setMinBondConfig(api, minValidatorBond);
missing cleanup in `afterEach`

2024-03-25 11:34 UTC, atodorov commented on cli/src/test/integration-tests/validate.test.ts
> +                expect(unbondResult.stdout).toContain('Transaction included at block');
Lines 140-145 are redundant. 

The amount already bonded is 900 CTC, just make the minBondAmount higher, e.g. 1000 and call validate.

2024-03-25 11:34 UTC, atodorov commented on cli/src/test/integration-tests/validate.test.ts
> +                await setMinBondConfig(api, minValidatorBond);
missing cleanup in afterEach

2024-03-25 11:38 UTC, DylanVerstraete commented on cli/src/test/integration-tests/wizard.test.ts
> +            } catch (error: any) {
I've noticed the accounts aren't cleaned up properly, every test is just bonding more to that account

2024-03-25 11:38 UTC, DylanVerstraete commented on cli/src/test/integration-tests/validate.test.ts
> +                expect(unbondResult.stdout).toContain('Transaction included at block');
Good idea

2024-03-25 12:55 UTC, atodorov commented on cli/src/test/integration-tests/wizard.test.ts
> +            } catch (error: any) {
Found the failing execution here (failed with timeout though):
https://github.com/gluwa/creditcoin3/actions/runs/8393365071/job/22988730430

maybe github action statuses did not get updated. Will check statuses again after current jobs finish.

2024-03-25 14:42 UTC, atodorov requested changes
Minor change requested, waiting on tests to complete.

2024-03-25 14:42 UTC, atodorov commented on cli/src/lib/staking/bond.ts
> +    if (BigInt(amount.toString()) < precision) {
Unrelated change, no? 

Variable `precision` isn't used anywhere else.

2024-03-25 14:44 UTC, DylanVerstraete commented on cli/src/lib/staking/bond.ts
> +    if (BigInt(amount.toString()) < precision) {
Made it a const in this file

2024-03-26 08:32 UTC, atodorov commented on cli/src/lib/staking/bond.ts
> +    if (BigInt(amount.toString()) < precision) {
I meant that this change isn't related to the actual scope of 1075, it's something extra which ideally should be proposed separately.

2024-03-26 08:57 UTC, atodorov requested changes

2024-03-26 08:57 UTC, atodorov commented on cli/src/test/integration-tests/validate.test.ts
> +        }, 90_000);
This block is valid only in the scope of `describe('when ALREADY bonded', () ` while the actual test that manipulates minValidatorBond is outside of this scope. 

This needs to be moved on line 41.

2024-03-26 10:44 UTC, DylanVerstraete commented on cli/src/lib/staking/bond.ts
> +    if (BigInt(amount.toString()) < precision) {
It's just a type alias to ` BigInt(MICROUNITS_PER_CTC)` which is now used in two places in this file

2024-03-26 15:53 UTC, DylanVerstraete commented
Extracted runtime here: https://github.com/gluwa/creditcoin3/pull/288

Will come back to the tests in a later stage

2024-03-26 15:53 UTC, closed without merging

2024-03-26 16:13 UTC, atodorov commented
Moving into Draft b/c of the test suite. Will pick it up later.

2024-04-01 12:32 UTC, atodorov approved these changes

2024-04-01 15:02 UTC, zacharyfrederick reviewed
LGTM. Did this really drop the smart contract integration test time by an hour?

2024-04-01 15:05 UTC, atodorov commented
> Did this really drop the smart contract integration test time by an hour?

No. This CI job has lots of fluctuations but this particupar PR has nothing to do with it.