feat: add test dry run chainspec files
gluwa/creditcoin3 pull request #397
Opened 2024-06-14 15:31 UTC by beqaabu

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-06-14 15:43 UTC, atodorov requested changes
New chainspecs contain bootnodes specification which we explicitly don't want. I don't think this has changed so the bootnodes should be removed.

2024-06-14 15:45 UTC, atodorov commented
Not sure if you should add the newly added chainspec to this test matrix:

```
  integration-test-chainspec:
    needs:
      - build-creditcoin-node
    strategy:
      fail-fast: false
      matrix:
        chainspec: [devnet, testnet]
```

It's probably a good idea to do that, but it may fail b/c we need a few well known accounts for testing purposes (and their private keys).

2024-06-17 06:43 UTC, beqaabu commented on node/src/chain_spec.rs
> +                        GrandpaId::from_string("5FPfCXHWGTqxHwpynt1yo5awMYGmCsMuCEeDaoyiZjwkTQqc")
These are some random accounts that we are imitating to be the initial validators for the chain. They are newly generated addresses. They are pre-refunded with some amount of tokens and have some stake bonded. This is all configured at genesis. We are launching this chain to a new cluster from block 0 and the finalization will be broken until we start the three initial validator nodes.

2024-06-17 07:09 UTC, atodorov commented on node/src/chain_spec.rs
> +                        GrandpaId::from_string("5FPfCXHWGTqxHwpynt1yo5awMYGmCsMuCEeDaoyiZjwkTQqc")
> the finalization will be broken until we start the three initial validator nodes.

Are we going to start these initial 3 nodes with private keys corresponding to the accounts listed above or are they going to be completely different ?

2024-06-17 07:35 UTC, beqaabu commented on node/src/chain_spec.rs
> +                        GrandpaId::from_string("5FPfCXHWGTqxHwpynt1yo5awMYGmCsMuCEeDaoyiZjwkTQqc")
Yes, we will start them with private keys corresponding to the accounts listed above and we will have finalization once all 3 of them are alive. Additionally, I can add private keys for these accounts in the source file if it makes life more convenient

2024-06-17 07:35 UTC, beqaabu commented on node/src/chain_spec.rs
> +                        BabeId::from_string("5HHLgjRbzx6AuTaMj4VaGnwF5rKhEVCAchNEh3PxYmafXZS9")
fixed

2024-06-17 07:36 UTC, atodorov commented on node/src/chain_spec.rs
> +                        GrandpaId::from_string("5FPfCXHWGTqxHwpynt1yo5awMYGmCsMuCEeDaoyiZjwkTQqc")
> I can add private keys for these accounts in the source file if it makes life more convenient

Defintiely not.

2024-06-17 07:49 UTC, beqaabu commented
> Not sure if you should add the newly added chainspec to this test matrix:
> 
> ```
>   integration-test-chainspec:
>     needs:
>       - build-creditcoin-node
>     strategy:
>       fail-fast: false
>       matrix:
>         chainspec: [devnet, testnet]
> ```
> 
> It's probably a good idea to do that, but it may fail b/c we need a few well known accounts for testing purposes (and their private keys).

Not sure how to handle this because we don't want to have well-known accounts in the authority set. The approach that we are trying to test out can be seen [here](https://gluwa.atlassian.net/wiki/spaces/CB/pages/1319665667/CC3+mainnet+migration)

2024-06-17 07:55 UTC, atodorov requested changes
See the gitleaks failure reported by MegaLinter.

2024-06-17 07:58 UTC, beqaabu commented
> See the gitleaks failure reported by MegaLinter.
> 
> If these are public keys or something that isn't supposed to be private then see `.gitleaksignore`

Yes, its Alice's public key, so I'll add it to `.gitleaksignore`

2024-06-17 08:29 UTC, DylanVerstraete commented on node/src/chain_spec.rs
> +pub fn dry_run_config() -> ChainSpec {
Not sure if we actually want to to track this in the source files. I would prefer just having a "dry run" chainspec file, which can be tracked in git if needed.

2024-06-17 08:42 UTC, beqaabu commented on node/src/chain_spec.rs
> +pub fn dry_run_config() -> ChainSpec {
I wanted to have the initial config reviewed first because the chainspec file is generated from there, once the review is good, I'll delete the unnecessary stuff from the `chain_spec.rs` file and have it read the config from a `dryRunSpecRaw.json` file

2024-06-17 09:18 UTC, atodorov approved these changes

2024-06-17 09:28 UTC, DylanVerstraete commented on node/src/chain_spec.rs
> +pub fn dry_run_config() -> ChainSpec {
Sounds good

2024-06-17 09:41 UTC, DylanVerstraete submitted a review, later dismissed

2024-06-17 10:50 UTC, atodorov approved these changes

2024-06-17 12:47 UTC, atodorov approved these changes

2024-06-17 13:26 UTC, merged