CSUB-1231: Change Benchmarking script and Release builds to use --profile=production
gluwa/creditcoin3 pull request #435
Opened 2024-08-05 19:33 UTC by BradleyOlson64

Enacting the same changes in CC3 as were made in CCNext here https://github.com/gluwa/creditcoin3-next/pull/137 

As described [here](https://gluwa.atlassian.net/browse/CSUB-1231) using --release to build for benchmarking and for live network images/artifacts results in network performance loss due to missing optimizations.

Anecdotally I've observed that execution time weights are about 10% worse using --release vs --profile=production

This pr doesn't try to change all CI jobs to use --profile=production though, because compiling that way takes about 2x longer. We don't want to waste loads of money on unnecessary compilation work.

2024-08-05 21:17 UTC, rustlang-dev approved these changes

2024-08-06 07:22 UTC, DylanVerstraete approved these changes

2024-08-07 07:27 UTC, atodorov requested changes
Minor change requested.

2024-08-07 07:27 UTC, atodorov commented on .github/workflows/release.yml
> +          args: --profile=production ${{ needs.setup.outputs.build_options}}
I think the same should be applied in `wasm.yml` as well, otherwise looks good.

2024-08-07 16:39 UTC, BradleyOlson64 commented on .github/workflows/release.yml
> +          args: --profile=production ${{ needs.setup.outputs.build_options}}
wasm.yml changed 👍

2024-08-07 17:03 UTC, BradleyOlson64 commented on .github/workflows/release.yml
> +          args: --profile=production ${{ needs.setup.outputs.build_options}}
Applying this change in `wasm.yml` created a rather confusing wasm build error in CI.

I'm not so sure this change is helpful, since `release.yml` appears to run its own independent wasm build. We can do without this right?

2024-08-07 17:27 UTC, atodorov commented on .github/workflows/release.yml
> +          args: --profile=production ${{ needs.setup.outputs.build_options}}
> We can do without this right?

IDK tbh. For Testnet & Mainnet releases we typically use the wasm blob from the release, e.g. the once created in release.yml. For automated Devnet upgrades we use the one from wasm.yaml. Both are compiled in the same way minus a few feature flags.

2024-08-07 17:30 UTC, atodorov commented on .github/workflows/release.yml
> +          args: --profile=production ${{ needs.setup.outputs.build_options}}
If I am reading the error logs at https://github.com/gluwa/creditcoin3/actions/runs/10288255898/job/28473252780 correctly it is a problem with how the profile information is specified, which I would think should be the same between the 2 yaml files but for some reason it isn't. 

Let's look into it tomorrow.

2024-08-08 14:04 UTC, atodorov commented on .github/workflows/release.yml
> +          args: --profile=production ${{ needs.setup.outputs.build_options}}
FTR: experimenting in https://github.com/gluwa/creditcoin3/pull/437. Let's not make any more changes here until we know what's going on.

2024-08-08 16:57 UTC, BradleyOlson64 commented
Closing this PR, as the team decided to include these changes upstream in CCNext and let them trickle down.

2024-08-08 16:57 UTC, closed without merging