Updated chainspecs for mainnet migration dry run 4
gluwa/creditcoin3 pull request #436
Opened 2024-08-06 19:20 UTC by BradleyOlson64

Need these updated specs to build the dry run image

2024-08-06 21:00 UTC, rustlang-dev approved these changes

2024-08-07 07:28 UTC, atodorov requested changes
See MegaLinter, .gitleaks!

2024-08-07 17:15 UTC, BradleyOlson64 commented
REMINDER: Do not squash while merging! This will break .gitleaks

2024-08-07 17:31 UTC, atodorov approved these changes

2024-08-07 18:41 UTC, dlebee approved these changes

2024-08-07 18:43 UTC, DylanVerstraete approved these changes

2024-08-07 18:56 UTC, merged