fix: correct precompile interface and json abi
gluwa/creditcoin3 pull request #462
Opened 2024-09-12 17:30 UTC by DylanVerstraete

# Description of proposed changes

fixes precompile interface and abi json

2024-09-13 09:27 UTC, atodorov requested changes
Need to fix this as well:
https://github.com/gluwa/creditcoin3/actions/runs/10835800728/job/30068106861?pr=462

2024-09-16 09:38 UTC, DylanVerstraete commented
This will require a runtime upgrade, @atodorov do I bump the runtime version in this PR? Also how do I chain the mainnet json files?

2024-09-16 09:45 UTC, atodorov requested changes
This https://github.com/gluwa/creditcoin3/actions/runs/10853245614/job/30121104364?pr=462 requires a version bump.

2024-09-16 12:01 UTC, atodorov approved these changes

2024-09-16 17:06 UTC, BradleyOlson64 approved these changes

2024-09-17 08:02 UTC, beqaabu approved these changes

2024-09-18 12:00 UTC, merged