Handle polkadot forks
gluwa/creditcoin3 pull request #483
Opened 2024-09-17 14:16 UTC by rustlang-dev

# Description of proposed changes

Handle polkadot forks

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-09-19 19:27 UTC, beqaabu reviewed
looking good so far but needs cleanup

2024-09-24 08:35 UTC, atodorov commented
From integration-tests-cli:

> Error: src/lib/staking/bond.ts(69,37): error TS2554: Expected 7 arguments, but got 6.
error Command failed with exit code 2.

This will have an impact on 2 fronts: 

1) Most likely Creditcoin 3 Staking Dashboard will be affected and will need to be updated as well
2) Older creditcoin-cli clients (e.g. ones which don't upgrade their docker images) won't be able to bond (probably other operations too) after the runtime upgrade occurs. That would generate lots of support calls from the community and some degree of bad publicity so it needs to be communicated well in advance.

2024-09-24 08:39 UTC, atodorov requested changes

2024-09-24 08:39 UTC, atodorov commented on precompiles/substrate-transfer/src/mock.rs
> +    // type MaxFreezes = frame_support::traits::VariantCountOf<RuntimeFreezeReason>;
IMO remove comments if not in use. Better keep the code base cleaner.

2024-10-11 09:39 UTC, atodorov requested changes
Minor issues noted. 

However while at it it would be great to rebase this PR in order to solve a conflict in Cargo.toml as well  as get rid of all the "Merge " commits currently present.

2024-10-11 09:39 UTC, atodorov commented on cc3.yml
> +    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
Triggers gitleaks -> https://github.com/gluwa/creditcoin3/actions/runs/11077595872/job/31400820960?pr=483

which seems like a false positive. You can disable it in `.gitleaksignore`, see the logs for more details. 

Note: I think when the commit hash changes .gitleaksignore needs to be updated!

2024-10-11 09:39 UTC, atodorov commented on cc3.yml
> +endpoint: wss://mainnet3.creditcoin.network
Suggestion: why not name this file `chopsticks.yml` or `chopsticks-config.yml` or something similar that would make it obvious what it is for ?

2024-10-11 09:39 UTC, atodorov commented on cc3.yml
> +
Nitpick: file can be reformatted with prettier -> 
https://github.com/gluwa/creditcoin3/actions/runs/11077595872/job/31400820960?pr=483

2025-07-09 12:46 UTC, closed without merging