Update precompile metadata mainnet
gluwa/creditcoin3 pull request #519
Opened 2024-11-05 11:35 UTC by beqaabu

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2024-11-05 12:15 UTC, atodorov requested changes
https://github.com/gluwa/creditcoin3/actions/runs/11683355803/job/32532535295?pr=519  crashes with: 

> Error: Input("Error opening spec file `main`: No such file or directory (os error 2)")

2024-11-05 12:27 UTC, beqaabu commented
> https://github.com/gluwa/creditcoin3/actions/runs/11683355803/job/32532535295?pr=519 crashed with:
> 
> > Error: Input("Error opening spec file `main`: No such file or directory (os error 2)")

I think thit error is fine on this branch because we don't have the mainnet spec file here (file was too large and we decided to keep it only on the `main` branch. It will be able to find that file as soon as this pr is merged to main

2024-11-05 13:00 UTC, atodorov commented
> file was too large and we decided to keep it only on the `main` branch

FTR this decision breaks runtime upgrade testing which will not be executed against mainnet data.

2024-11-05 22:50 UTC, BradleyOlson64 approved these changes

2024-11-06 10:08 UTC, DylanVerstraete approved these changes

2024-11-06 10:09 UTC, merged