[CSUB-787] Port over CLI to CC3 (with dual accounts)
gluwa/creditcoin3 pull request #76
Opened 2023-11-15 15:51 UTC by pLabarta

# Description of proposed changes

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2023-11-22 13:26 UTC, atodorov requested changes
I tested all available commands and overall they look good. Added a few comments and questions. I am OK with transfering these into Jira tickets and resolving them later.

2023-11-22 13:35 UTC, pLabarta commented on cli/package.json
> +        "creditcoin3": "dist/cli.js"
`index.js` is supposed to be the entrypoint to the library/package, while `cli.js` is the entrypoint to the actual CLI tool. I would keep them as different files, but I'm ok with merging them too.

2023-11-22 13:38 UTC, pLabarta commented on cli/src/lib/parsing.ts
> +        throw new Error('Percent value must be between 0 and 100');
Its ok to have a validator with 100% commission. Did the wording make it seem like it should not be possible?

2023-11-22 13:55 UTC, pLabarta commented on cli/src/commands/showAddress.ts
> +    cmd.option('--index [index]', 'Specify account index');
Oh, this was left from the EVM accounts, must be removed.

2023-11-22 13:57 UTC, pLabarta commented on cli/src/commands/send.ts
> +    const tx = api.tx.balances.transfer(recipient, amount.toString());
It will probably be widely used by validators and nominators. Currently it is not supported by our CLI. This will probably require its own PR to properly support this use case.

2023-11-22 16:05 UTC, pLabarta commented on cli/src/commands/session/rotateKeys.ts
> +    const newKeys = await api.rpc.author.rotateKeys();
Rotate keys does not require any account, but it requires access to the "unsafe" RPCs, either by running the node with the required flag or by running the CLI in the same machine as the node.

Would some info about this in the description help?

2023-11-23 08:57 UTC, atodorov commented on cli/src/commands/session/rotateKeys.ts
> +    const newKeys = await api.rpc.author.rotateKeys();
> Would some info about this in the description help?

I think yes.

2023-11-23 09:00 UTC, atodorov commented on cli/src/lib/parsing.ts
> +        throw new Error('Percent value must be between 0 and 100');
> Did the wording make it seem like it should not be possible?

No, wording is fine. 

I expected that 100% commission wasn't possible b/c it doesn't make sense from the POV of nominators. However Polkadot JS Apps also supports adding a validator with 100% commission so marking this as resolved.

2023-11-23 15:21 UTC, atodorov commented on cli/src/commands/send.ts
> +    const tx = api.tx.balances.transfer(recipient, amount.toString());
CSUB-912

2023-11-23 16:21 UTC, atodorov commented on cli/src/commands/status.ts
> +    cmd.option('--address [address]', 'Validator address to get status for');
```suggestion
    cmd.option('--address [address]', 'Address to get status for');
```

2023-11-23 16:26 UTC, pLabarta commented on cli/src/commands/staking/bond.ts
> +        parseChoiceOrExit(inputOrDefault(options.rewardDestination, 'Staked'), ['Staked', 'caller']),
Whoops, must have landed there when replacing `stash` on variable names

2023-11-23 16:27 UTC, pLabarta commented on cli/src/cli.ts
> +    cmd.option('--use-ecdsa', 'Use ECDSA and a private key instead of a mnemonic phrase');
Opening a ticket for this one!

2023-11-23 16:30 UTC, pLabarta commented on cli/src/commands/staking/setKeys.ts
> +import { Command, OptionValues } from 'commander';
I see set keys as a command related to setting up validators, while session could involve other use-cases (we dont have any at the moment tho) and do not require an account. They just involve interacting with the node directly.

I was thinking to include a insertKeys command for adding new predefined keys to a node and automating some of our ops tasks, that one could go into the session dir.

2023-11-23 19:31 UTC, atodorov approved these changes

2023-11-24 12:00 UTC, merged