CSUB-833: Pallet bridge (Draft)
gluwa/creditcoin3 pull request #77
Opened 2023-11-15 19:08 UTC by zacharyfrederick

Need to add weights and work on more unit tests. Also, have some questions about the flowcharts from the document.

2023-11-16 03:35 UTC, nathanwhit requested changes
A few quick comments

2023-11-16 03:35 UTC, nathanwhit commented on pallets/bridge/src/types.rs
> +pub struct BurnId(pub u64);
I know this isn't in the doc, but I think we should change this to

```rust
pub enum BurnId {
    Creditcoin2(u64)
}
```

So that we could add more in the future without needing a storage migration (for instance if we want to use a TX hash to refer to a burn on ethereum)

2023-11-16 03:35 UTC, nathanwhit commented on pallets/bridge/src/lib.rs
> +        TestEvent,
Remove

2023-11-16 03:35 UTC, nathanwhit commented on pallets/bridge/src/lib.rs
> +                in_progress.status != CollectionStatus::Completed,
Feels weird that you can have things in the `InProgress` storage that aren't in progress

2023-11-19 18:52 UTC, zacharyfrederick commented on pallets/bridge/src/types.rs
> +pub struct BurnId(pub u64);
This is a good idea. I used a simple enum and a switch statement for the current implementation. It might be smart to move all cc2 functionality into its own pallet. Have each bridge implementation fulfill a trait with `collect, approve, and reject` calls and then have a bridge pallet that ties them all together and exposes the public interface. That would make testing and expanding all the bridge sources easier than keeping a single pallet.

2023-11-20 19:39 UTC, merged