Code review
gluwa/creditcoin3 pull request #81
Opened 2023-11-17 07:49 UTC by cuteolaf

# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

2023-11-17 07:51 UTC, cuteolaf commented
@atodorov @nathanwhit

2023-11-17 12:57 UTC, atodorov requested changes
Some changes requested. Also needs rebase onto latest `dev` b/c of some changes to README (should not conflict though).

2023-11-17 13:04 UTC, cuteolaf commented on runtime/src/lib.rs
> +    type MaxAuthorities = ConstU32<100>;
At first, I also thought so, but we might need to use different values for the same `MaxAuthorities` trait of `pallet-aura` and `pallet-grandpa`. Actually, this is why I removed the constant definition and used a hard-coded constant value instead.

2023-11-17 13:06 UTC, cuteolaf commented
thanks for your review, @atodorov

2023-11-17 13:13 UTC, pLabarta commented on README.md
> -This template was originally forked from the
Yeah, would remove it

2023-11-20 22:34 UTC, nathanwhit commented on runtime/src/lib.rs
> +    type MaxAuthorities = ConstU32<100>;
The value of `MaxAuthorities` should always be the same for BABE and grandpa. The authority set is identical, so the maximums should be identical as well. So I agree with @atodorov on this. one, we should update the second instance of `MaxAuthorities` to use the shared constant.

2023-11-21 11:02 UTC, atodorov requested changes
@cuteolaf can you rebase instead of merge and maybe squash some commits together for better readability. 

Will requite another version bump afterwards. 

Still needs decisionwhat the maximum number of authorities should be.

2023-11-21 11:02 UTC, atodorov commented on runtime/src/lib.rs
> +    pub const MaxAuthorities: u32 = 32;
@nathanwhit interesting, before this change MaxAuthorities for GRANDPA was 32 while MaxAuthorities for BABE was 100. I'm curious why it didn't break something and which value should be kept as the canonical one ?

2023-11-27 15:05 UTC, pLabarta commented on runtime/src/lib.rs
> +    pub const MaxAuthorities: u32 = 32;
CC2 is currently running more than 32 validators in production. I would keep 100 MaxAuthorities to support a similar number of validators on CC3.

2023-12-11 12:34 UTC, cuteolaf commented on runtime/src/lib.rs
> +    pub const MaxAuthorities: u32 = 32;
resolved. @atodorov @pLabarta

2023-12-11 13:04 UTC, atodorov requested changes
See failure in https://github.com/gluwa/creditcoin3/actions/runs/7167525956/job/19514697597?pr=81. 

Also can you 'rebase' instead of 'merge' ?

2026-04-08 15:46 UTC, atodorov commented
Closing due to inactivity.

2026-04-08 15:46 UTC, closed without merging

2026-04-08 19:11 UTC, cuteolaf commented
Is this project still active?